// Lesson content for Hokkien Beginner Track
import { Lesson, Unit, Dialect } from '../types';

export const UNITS: Unit[] = [
  {
    id: 'hokkien-u1',
    dialect: 'hokkien',
    unit: 1,
    title: 'Greetings',
    description: 'Basic greetings and essentials',
    lessons: 5,
    duration: '25 minutes',
  },
  {
    id: 'hokkien-u2',
    dialect: 'hokkien',
    unit: 2,
    title: 'Numbers & Counting',
    description: 'Numbers 1-100, prices, market',
    lessons: 5,
    duration: '30 minutes',
  },
  {
    id: 'hokkien-u3',
    dialect: 'hokkien',
    unit: 3,
    title: 'Family',
    description: 'Family members and relationships',
    lessons: 6,
    duration: '35 minutes',
  },
  // NEW: Cantonese Units
  {
    id: 'cantonese-u1',
    dialect: 'cantonese',
    unit: 1,
    title: 'Greetings',
    description: 'Basic greetings and essentials',
    lessons: 5,
    duration: '25 minutes',
  },
  {
    id: 'cantonese-u2',
    dialect: 'cantonese',
    unit: 2,
    title: 'Numbers & Counting',
    description: 'Numbers 1-100, prices, shopping',
    lessons: 5,
    duration: '30 minutes',
  },
  // NEW: Hakka Units
  {
    id: 'hakka-u1',
    dialect: 'hakka',
    unit: 1,
    title: 'Greetings',
    description: 'Basic greetings and essentials',
    lessons: 5,
    duration: '25 minutes',
  },
  {
    id: 'hakka-u2',
    dialect: 'hakka',
    unit: 2,
    title: 'Numbers & Counting',
    description: 'Numbers 1-100, prices, shopping',
    lessons: 5,
    duration: '30 minutes',
  },
  // NEW: Food & Drinks Units
  {
    id: 'hokkien-u4',
    dialect: 'hokkien',
    unit: 4,
    title: 'Food & Drinks',
    description: 'Ordering food, drinks, restaurant vocabulary',
    lessons: 5,
    duration: '35 minutes',
  },
  {
    id: 'cantonese-u3',
    dialect: 'cantonese',
    unit: 3,
    title: 'Food & Drinks',
    description: 'Ordering food, drinks, restaurant vocabulary',
    lessons: 5,
    duration: '35 minutes',
  },
  {
    id: 'hakka-u3',
    dialect: 'hakka',
    unit: 3,
    title: 'Food & Drinks',
    description: 'Ordering food, drinks, restaurant vocabulary',
    lessons: 5,
    duration: '35 minutes',
  },
  // NEW: Travel & Directions Units
  {
    id: 'hokkien-u5',
    dialect: 'hokkien',
    unit: 5,
    title: 'Travel & Directions',
    description: 'Getting around, transportation, directions',
    lessons: 5,
    duration: '35 minutes',
  },
  {
    id: 'cantonese-u4',
    dialect: 'cantonese',
    unit: 4,
    title: 'Travel & Directions',
    description: 'Getting around, transportation, directions',
    lessons: 5,
    duration: '35 minutes',
  },
  {
    id: 'hakka-u4',
    dialect: 'hakka',
    unit: 4,
    title: 'Travel & Directions',
    description: 'Getting around, transportation, directions',
    lessons: 5,
    duration: '35 minutes',
  },
  // NEW: Emotions Units
  {
    id: 'hokkien-u6',
    dialect: 'hokkien',
    unit: 6,
    title: 'Emotions',
    description: 'Expressing feelings, moods, and health',
    lessons: 5,
    duration: '30 minutes',
  },
  {
    id: 'cantonese-u5',
    dialect: 'cantonese',
    unit: 5,
    title: 'Emotions',
    description: 'Expressing feelings, moods, and health',
    lessons: 5,
    duration: '30 minutes',
  },
  {
    id: 'hakka-u5',
    dialect: 'hakka',
    unit: 5,
    title: 'Emotions',
    description: 'Expressing feelings, moods, and health',
    lessons: 5,
    duration: '30 minutes',
  },
  // NEW: Hakka Time & Weather Units
  {
    id: 'hakka-u6',
    dialect: 'hakka',
    unit: 6,
    title: 'Time',
    description: 'Telling time, days, weeks, months',
    lessons: 5,
    duration: '30 minutes',
  },
  {
    id: 'hakka-u7',
    dialect: 'hakka',
    unit: 7,
    title: 'Weather',
    description: 'Weather conditions, seasons, climate',
    lessons: 5,
    duration: '30 minutes',
  },
];

export const LESSONS: Lesson[] = [
  // Unit 1: Greetings
  {
    id: 'hokkien-u1-l1',
    dialect: 'hokkien',
    unit: 1,
    lesson: 1,
    title: 'Basic Greetings',
    subtitle: 'Hello, Thank you',
    duration: '5 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'h1-1', phrase: { chinese: '你好', romanization: 'lí-hó', english: 'Hello', tone: 2 }},
      { id: 'h1-2', phrase: { chinese: '食飽未?', romanization: 'chia̤h-bē-bē', english: 'Have you eaten?', tone: 7 }},
      { id: 'h1-3', phrase: { chinese: '去叨位?', romanization: 'khì-to-ūi', english: 'Where are you going?', tone: 5 }},
      { id: 'h1-4', phrase: { chinese: '好', romanization: 'hó', english: 'Good / Okay', tone: 3 }},
      { id: 'h1-5', phrase: { chinese: '毋好', romanization: 'm̄-hó', english: 'Not good', tone: 7 }},
      { id: 'h1-6', phrase: { chinese: '恬', romanization: 'tiām', english: 'Quiet / Silent', tone: 5 }},
      { id: 'h1-7', phrase: { chinese: '緊', romanization: 'kín', english: 'Fast / Quickly', tone: 2 }},
    ],
    dialogue: {
      id: 'd1',
      title: 'Meeting a Friend',
      lines: [
        { speaker: 'A', chinese: '你好!', romanization: 'lí-hó!', english: 'Hello!' },
        { speaker: 'B', chinese: '你好! 食飽未?', romanization: 'lí-hó! chia̤h-bē-bē?', english: 'Hello! Have you eaten?' },
        { speaker: 'A', chinese: '食飽啊，你呢?', romanization: 'chia̤h-bē-a, lí-ne?', english: 'I have, how about you?' },
      ],
    },
    quiz: [
      {
        id: 'q1',
        type: 'listening',
        question: "What does '你好' mean?",
        options: ['Goodbye', 'Hello', 'Thank you', 'Good morning'],
        correctIndex: 1,
      },
    ],
    culturalNote: "In Singapore, asking '食飽未?' (Have you eaten?) is not just about food — it's a way of showing care! Your auntie might force-feed you even if you say yes!",
  },
  {
    id: 'hokkien-u1-l2',
    dialect: 'hokkien',
    unit: 1,
    lesson: 2,
    title: 'Gratitude',
    subtitle: 'Thank you and responses',
    duration: '5 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'h2-1', phrase: { chinese: '感謝', romanization: 'kám-siā', english: 'Thank you (formal)', tone: 3 }},
      { id: 'h2-2', phrase: { chinese: '多谢', romanization: 'to-siā', english: 'Thanks (casual)', tone: 1 }},
      { id: 'h2-3', phrase: { chinese: '免客氣', romanization: 'bián-kheh-khì', english: "Don't be客气", tone: 1 }},
      { id: 'h2-4', phrase: { chinese: 'sorry', romanization: 'sóh-lí', english: 'Sorry', tone: 1 }},
      { id: 'h2-5', phrase: { chinese: '原諒', romanization: 'goân-liōng', english: 'Excuse me / Forgive', tone: 5 }},
      { id: 'h2-6', phrase: { chinese: '無要緊', romanization: 'bô-iàu-kín', english: 'Never mind / It\'s okay', tone: 5 }},
    ],
    quiz: [
      {
        id: 'q2',
        type: 'listening',
        question: "Which phrase means 'Thank you' informally?",
        options: ['感謝', '多谢', '恬', '好'],
        correctIndex: 1,
      },
    ],
    culturalNote: "In informal situations, '多谢' (to-siā) is more commonly used than the formal '感謝'. Using the right level of politeness shows respect!",
  },
  {
    id: 'hokkien-u1-l3',
    dialect: 'hokkien',
    unit: 1,
    lesson: 3,
    title: 'Getting Attention',
    subtitle: 'Calling someone',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'h3-1', phrase: { chinese: '喂', romanization: 'wê / óh', english: 'Hey (phone)', tone: 2 }},
      { id: 'h3-2', phrase: { chinese: '恁爸', romanization: 'lín-pē', english: 'Hey (casual, male)', tone: 2 }},
      { id: 'h3-3', phrase: { chinese: '小姐', romanization: 'siáu-chiá', english: 'Miss / Young lady', tone: 3 }},
      { id: 'h3-4', phrase: { chinese: '先生', romanization: 'sian-sinn', english: 'Mister / Sir', tone: 1 }},
      { id: 'h3-5', phrase: { chinese: '朋友', romanization: 'pêng-iú', english: 'Friend', tone: 5 }},
    ],
    quiz: [
      {
        id: 'q3',
        type: 'listening',
        question: "Which is appropriate for a young woman?",
        options: ['恁爸', '小姐', '先生', '喂'],
        correctIndex: 1,
      },
    ],
    culturalNote: "In Singapore, it's common to use 'Uncle' (阿叔) and 'Auntie' (阿嫂) to respectfully address older strangers, even hawkers!",
  },
  {
    id: 'hokkien-u1-l4',
    dialect: 'hokkien',
    unit: 1,
    lesson: 4,
    title: 'Farewells',
    subtitle: 'Goodbye expressions',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'h4-1', phrase: { chinese: '再見', romanization: 'chài-kiàn', english: 'Goodbye', tone: 5 }},
      { id: 'h4-2', phrase: { chinese: '明仔見', romanization: 'miâ-á-kìⁿ', english: 'See you tomorrow', tone: 1 }},
      { id: 'h4-3', phrase: { chinese: '慢走', romanization: 'bān-cháu', english: 'Take care (when leaving)', tone: 6 }},
      { id: 'h4-4', phrase: { chinese: '下次見', romanization: 'hē-chhù-kìⁿ', english: 'See you next time', tone: 5 }},
      { id: 'h4-5', phrase: { chinese: '拜拜', romanization: 'pài-pài', english: 'Bye bye', tone: 3 }},
    ],
    quiz: [
      {
        id: 'q4',
        type: 'listening',
        question: "What do you say when you're leaving and want someone to take care?",
        options: ['再見', '慢走', '明仔見', '拜拜'],
        correctIndex: 1,
      },
    ],
    culturalNote: "'拜拜' is the Hokkien adaptation of English 'bye-bye' and is commonly used among younger Singaporeans!",
  },
  {
    id: 'hokkien-u1-l5',
    dialect: 'hokkien',
    unit: 1,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      {
        id: 'q5-1',
        type: 'listening',
        question: "How do you say 'Hello' in Hokkien?",
        options: ['再見', '你好', '感謝', '好'],
        correctIndex: 1,
      },
      {
        id: 'q5-2',
        type: 'listening',
        question: "What does '食飽未?' mean?",
        options: ['Where are you going?', 'Thank you', 'Have you eaten?', 'Goodbye'],
        correctIndex: 2,
      },
      {
        id: 'q5-3',
        type: 'reading',
        question: "Choose the formal thank you:",
        options: ['多谢', '感謝', '恬', '毋好'],
        correctIndex: 1,
      },
    ],
    culturalNote: "Congratulations on completing Unit 1! You've learned the basics of greeting someone in Hokkien. Practice these phrases with family or friends!",
  },

  // CANTONESE UNIT 1: GREETINGS
  {
    id: 'cantonese-u1-l1',
    dialect: 'cantonese',
    unit: 1,
    lesson: 1,
    title: 'Basic Greetings',
    subtitle: 'Hello, Good morning',
    duration: '5 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c1-1', phrase: { chinese: '你好', romanization: 'nei5 hou2', english: 'Hello', tone: 5 }},
      { id: 'c1-2', phrase: { chinese: '早晨', romanization: 'zou2 san4', english: 'Good morning', tone: 2 }},
      { id: 'c1-3', phrase: { chinese: '午安', romanization: 'ng5 on1', english: 'Good afternoon', tone: 1 }},
      { id: 'c1-4', phrase: { chinese: '晚安', romanization: 'maan6 on1', english: 'Good evening', tone: 1 }},
      { id: 'c1-5', phrase: { chinese: '食咗未呀?', romanization: 'zik6 zo2 mei6', english: 'Have you eaten?', tone: 6 }},
      { id: 'c1-6', phrase: { chinese: '好好', romanization: 'hou2 hou2', english: 'Good', tone: 2 }},
      { id: 'c1-7', phrase: { chinese: '晤好', romanization: 'm4 hou2', english: 'Not good', tone: 4 }},
    ],
    dialogue: { id: 'cd1', title: 'Meeting a Friend', lines: [
      { speaker: 'A', chinese: '早晨!', romanization: 'zou2 san4!', english: 'Good morning!' },
      { speaker: 'B', chinese: '早晨! 食咗未呀?', romanization: 'zou2 san4! zik6 zo2 mei6?', english: 'Good morning! Have you eaten?' },
    ]},
    quiz: [{ id: 'cq1', type: 'listening', question: "What does '早晨' mean?", options: ['Goodbye', 'Good morning', 'Thank you', 'Good night'], correctIndex: 1 }],
    culturalNote: "In Hong Kong, asking '食咗未呀?' is a warm greeting showing care!",
  },
  {
    id: 'cantonese-u1-l2',
    dialect: 'cantonese',
    unit: 1,
    lesson: 2,
    title: 'Gratitude',
    subtitle: 'Thank you and responses',
    duration: '5 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c2-1', phrase: { chinese: '多謝', romanization: 'do1 ze6', english: 'Thank you', tone: 1 }},
      { id: 'c2-2', phrase: { chinese: '唔該', romanization: 'm4 goi1', english: 'Thanks / Sorry', tone: 1 }},
      { id: 'c2-3', phrase: { chinese: '對晤住', romanization: 'deoi3 m4 zyu6', english: 'Sorry', tone: 6 }},
      { id: 'c2-4', phrase: { chinese: '晤緊要', romanization: 'm4 gan2 jiu3', english: "It's okay", tone: 3 }},
    ],
    quiz: [{ id: 'cq2', type: 'listening', question: "Which means 'Thank you'?", options: ['多謝', '對晤住', '晤好', '晚安'], correctIndex: 0 }],
    culturalNote: "'唔該' is versatile - used for thanks and excuse me!",
  },
  {
    id: 'cantonese-u1-l3',
    dialect: 'cantonese',
    unit: 1,
    lesson: 3,
    title: 'Getting Attention',
    subtitle: 'Calling someone',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c3-1', phrase: { chinese: '喂', romanization: 'wai3', english: 'Hey', tone: 3 }},
      { id: 'c3-2', phrase: { chinese: '大佬', romanization: 'daai6 lou2', english: 'Big brother', tone: 3 }},
      { id: 'c3-3', phrase: { chinese: '小姐', romanization: 'siu2 ze2', english: 'Miss', tone: 2 }},
      { id: 'c3-4', phrase: { chinese: '先生', romanization: 'sin1 saang1', english: 'Sir', tone: 1 }},
      { id: 'c3-5', phrase: { chinese: '朋友', romanization: 'pang4 jau5', english: 'Friend', tone: 5 }},
    ],
    quiz: [{ id: 'cq3', type: 'listening', question: "For a young woman?", options: ['大佬', '小姐', '先生', '喂'], correctIndex: 1 }],
    culturalNote: "Use 小姐 and 先生 for polite addressing of strangers.",
  },
  {
    id: 'cantonese-u1-l4',
    dialect: 'cantonese',
    unit: 1,
    lesson: 4,
    title: 'Farewells',
    subtitle: 'Goodbye expressions',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c4-1', phrase: { chinese: '拜拜', romanization: 'baai1 baai1', english: 'Bye bye', tone: 1 }},
      { id: 'c4-2', phrase: { chinese: '聽日見', romanization: 'ting1 jat6 gin3', english: 'See you tomorrow', tone: 3 }},
      { id: 'c4-3', phrase: { chinese: '慢走', romanization: 'maan6 zau2', english: 'Take care', tone: 2 }},
      { id: 'c4-4', phrase: { chinese: '下次見', romanization: 'haa6 ci3 gin3', english: 'See you next time', tone: 3 }},
      { id: 'c4-5', phrase: { chinese: '再見', romanization: 'zoi3 gin3', english: 'Goodbye', tone: 3 }},
    ],
    quiz: [{ id: 'cq4', type: 'listening', question: "What does '聽日見' mean?", options: ['Goodbye', 'See you tomorrow', 'Take care', 'Bye'], correctIndex: 1 }],
    culturalNote: "'拜拜' is borrowed from English - common among youth!",
  },
  {
    id: 'cantonese-u1-l5',
    dialect: 'cantonese',
    unit: 1,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'cq5-1', type: 'listening', question: "'Hello' in Cantonese?", options: ['再見', '你好', '多謝', '晤好'], correctIndex: 1 },
      { id: 'cq5-2', type: 'listening', question: "'食咗未呀?' means?", options: ['Thank you', 'Where going?', 'Have you eaten?', 'Goodbye'], correctIndex: 2 },
    ],
    culturalNote: "Great job completing Cantonese Unit 1!",
  },

  // CANTONESE UNIT 2: NUMBERS
  {
    id: 'cantonese-u2-l1',
    dialect: 'cantonese',
    unit: 2,
    lesson: 1,
    title: 'Numbers 1-10',
    subtitle: 'Basic counting',
    duration: '6 minutes • 10 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c5-1', phrase: { chinese: '一', romanization: 'jat1', english: 'One', tone: 1 }},
      { id: 'c5-2', phrase: { chinese: '二', romanization: 'ji6', english: 'Two', tone: 6 }},
      { id: 'c5-3', phrase: { chinese: '三', romanization: 'saam1', english: 'Three', tone: 1 }},
      { id: 'c5-4', phrase: { chinese: '四', romanization: 'sei3', english: 'Four', tone: 3 }},
      { id: 'c5-5', phrase: { chinese: '五', romanization: 'ng5', english: 'Five', tone: 5 }},
      { id: 'c5-6', phrase: { chinese: '六', romanization: 'luk6', english: 'Six', tone: 6 }},
      { id: 'c5-7', phrase: { chinese: '七', romanization: 'cat1', english: 'Seven', tone: 1 }},
      { id: 'c5-8', phrase: { chinese: '八', romanization: 'baat3', english: 'Eight', tone: 3 }},
      { id: 'c5-9', phrase: { chinese: '九', romanization: 'gau2', english: 'Nine', tone: 2 }},
      { id: 'c5-10', phrase: { chinese: '十', romanization: 'sap6', english: 'Ten', tone: 6 }},
    ],
    quiz: [{ id: 'cq6', type: 'listening', question: "'五' is what number?", options: ['3', '5', '7', '9'], correctIndex: 1 }],
    culturalNote: "Cantonese numbers differ from Mandarin pronunciation!",
  },
  {
    id: 'cantonese-u2-l2',
    dialect: 'cantonese',
    unit: 2,
    lesson: 2,
    title: 'Numbers 11-100',
    subtitle: 'Higher numbers',
    duration: '6 minutes • 8 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c6-1', phrase: { chinese: '十一', romanization: 'sap6 jat1', english: 'Eleven', tone: 1 }},
      { id: 'c6-2', phrase: { chinese: '二十', romanization: 'ja6 sap6', english: 'Twenty', tone: 6 }},
      { id: 'c6-3', phrase: { chinese: '二十五', romanization: 'ja6 sap6 ng5', english: 'Twenty-five', tone: 5 }},
      { id: 'c6-4', phrase: { chinese: '五十', romanization: 'ng5 sap6', english: 'Fifty', tone: 5 }},
      { id: 'c6-5', phrase: { chinese: '一百', romanization: 'jat1 baak3', english: 'One hundred', tone: 3 }},
      { id: 'c6-6', phrase: { chinese: '一千', romanization: 'jat1 cin1', english: 'One thousand', tone: 1 }},
    ],
    quiz: [{ id: 'cq7', type: 'listening', question: "'一百' means?", options: ['Ten', 'One hundred', 'One thousand', 'Eleven'], correctIndex: 1 }],
    culturalNote: "Cantonese compound numbers are similar to Mandarin!",
  },
  {
    id: 'cantonese-u2-l3',
    dialect: 'cantonese',
    unit: 2,
    lesson: 3,
    title: 'Prices & Money',
    subtitle: 'Shopping vocabulary',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c7-1', phrase: { chinese: '幾錢?', romanization: 'gei2 cin2?', english: 'How much?', tone: 2 }},
      { id: 'c7-2', phrase: { chinese: '港幣', romanization: 'gong2 bai6', english: 'HKD', tone: 6 }},
      { id: 'c7-3', phrase: { chinese: '貴', romanization: 'gwai3', english: 'Expensive', tone: 3 }},
      { id: 'c7-4', phrase: { chinese: '平', romanization: 'peng4', english: 'Cheap', tone: 4 }},
    ],
    dialogue: { id: 'cd2', title: 'Shopping', lines: [
      { speaker: 'A', chinese: '呢個幾錢?', romanization: 'ni1 go3 gei2 cin2?', english: 'How much is this?' },
      { speaker: 'B', chinese: '五十蚊', romanization: 'ng5 sap6 man1', english: 'Fifty dollars' },
    ]},
    quiz: [{ id: 'cq8', type: 'listening', question: "Ask 'How much?'", options: ['幾錢?', '貴', '平', '港幣'], correctIndex: 0 }],
    culturalNote: "Bargaining is common in Hong Kong markets!",
  },
  {
    id: 'cantonese-u2-l4',
    dialect: 'cantonese',
    unit: 2,
    lesson: 4,
    title: 'Counting Items',
    subtitle: 'Measures and counters',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'c8-1', phrase: { chinese: '個', romanization: 'go3', english: 'Classifier (items)', tone: 3 }},
      { id: 'c8-2', phrase: { chinese: '斤', romanization: 'gan1', english: 'Catty (500g)', tone: 1 }},
      { id: 'c8-3', phrase: { chinese: '隻', romanization: 'zoek3', english: 'Classifier (animals)', tone: 3 }},
      { id: 'c8-4', phrase: { chinese: '件', romanization: 'gin6', english: 'Classifier (clothes)', tone: 6 }},
    ],
    quiz: [{ id: 'cq9', type: 'listening', question: "Classifier for apples?", options: ['隻', '個', '件', '斤'], correctIndex: 1 }],
    culturalNote: "'斤' is about 500g in Hong Kong markets!",
  },
  {
    id: 'cantonese-u2-l5',
    dialect: 'cantonese',
    unit: 2,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'cq10-1', type: 'listening', question: "'Twenty-five'?", options: ['二十五', '二十', '十五', '五十'], correctIndex: 0 },
      { id: 'cq10-2', type: 'listening', question: "'平' means?", options: ['Expensive', 'Cheap', 'How much', 'Money'], correctIndex: 1 },
    ],
    culturalNote: "Cantonese Unit 2 complete! You can now shop and count!",
  },

  // HAKKA UNIT 1: GREETINGS
  {
    id: 'hakka-u1-l1',
    dialect: 'hakka',
    unit: 1,
    lesson: 1,
    title: 'Basic Greetings',
    subtitle: 'Hello, Good morning',
    duration: '5 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk1-1', phrase: { chinese: '你好', romanization: 'ni2 hou3', english: 'Hello', tone: 3 }},
      { id: 'hk1-2', phrase: { chinese: '朝晨好', romanization: 'zau1 sin2 hou3', english: 'Good morning', tone: 2 }},
      { id: 'hk1-3', phrase: { chinese: '日安', romanization: 'ngit5 on1', english: 'Good afternoon', tone: 1 }},
      { id: 'hk1-4', phrase: { chinese: '暗晡好', romanization: 'am3 bu1 hou3', english: 'Good evening', tone: 3 }},
      { id: 'hk1-5', phrase: { chinese: '食吂?', romanization: 'sii2 mang1?', english: 'Have you eaten?', tone: 1 }},
      { id: 'hk1-6', phrase: { chinese: '好', romanization: 'hou3', english: 'Good', tone: 3 }},
      { id: 'hk1-7', phrase: { chinese: '毋好', romanization: 'm2 hou3', english: 'Not good', tone: 3 }},
    ],
    quiz: [{ id: 'hkq1', type: 'listening', question: "'朝晨好' means?", options: ['Goodbye', 'Good morning', 'Thank you', 'Good night'], correctIndex: 1 }],
    culturalNote: "Hakka is spoken by Hakka people in Taiwan, Malaysia and beyond!",
  },
  {
    id: 'hakka-u1-l2',
    dialect: 'hakka',
    unit: 1,
    lesson: 2,
    title: 'Gratitude',
    subtitle: 'Thank you and responses',
    duration: '5 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk2-1', phrase: { chinese: '多謝', romanization: 'do1 sia4', english: 'Thank you', tone: 4 }},
      { id: 'hk2-2', phrase: { chinese: '承蒙', romanization: 'sin2 mong4', english: 'Thank you (formal)', tone: 4 }},
      { id: 'hk2-3', phrase: { chinese: '麻煩', romanization: 'ma2 fan4', english: 'Sorry', tone: 4 }},
      { id: 'hk2-4', phrase: { chinese: '對毋住', romanization: 'dui3 m2 cu4', english: 'Sorry', tone: 4 }},
    ],
    quiz: [{ id: 'hkq2', type: 'listening', question: "'Thank you' in Hakka?", options: ['多謝', '對毋住', '麻煩', '毋好'], correctIndex: 0 }],
    culturalNote: "'多謝' is standard thank you in Hakka!",
  },
  {
    id: 'hakka-u1-l3',
    dialect: 'hakka',
    unit: 1,
    lesson: 3,
    title: 'Getting Attention',
    subtitle: 'Calling someone',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk3-1', phrase: { chinese: '喂', romanization: 've4', english: 'Hey', tone: 4 }},
      { id: 'hk3-2', phrase: { chinese: '大佬', romanization: 'tai4 lo3', english: 'Big brother', tone: 3 }},
      { id: 'hk3-3', phrase: { chinese: '小姐', romanization: 'siau3 zia3', english: 'Miss', tone: 3 }},
      { id: 'hk3-4', phrase: { chinese: '先生', romanization: 'sien1 sen1', english: 'Sir', tone: 1 }},
      { id: 'hk3-5', phrase: { chinese: '朋友', romanization: 'pen5 iu3', english: 'Friend', tone: 3 }},
    ],
    quiz: [{ id: 'hkq3', type: 'listening', question: "For a young woman?", options: ['大佬', '喂', '小姐', '先生'], correctIndex: 2 }],
    culturalNote: "Respectful titles are important in Hakka culture!",
  },
  {
    id: 'hakka-u1-l4',
    dialect: 'hakka',
    unit: 1,
    lesson: 4,
    title: 'Farewells',
    subtitle: 'Goodbye expressions',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk4-1', phrase: { chinese: '再見', romanization: 'zai4 gien4', english: 'Goodbye', tone: 4 }},
      { id: 'hk4-2', phrase: { chinese: '明旦見', romanization: 'min2 tan4 gien4', english: 'See you tomorrow', tone: 4 }},
      { id: 'hk4-3', phrase: { chinese: '慢走', romanization: 'man4 zu3', english: 'Take care', tone: 3 }},
      { id: 'hk4-4', phrase: { chinese: '下次見', romanization: 'ha4 ci4 gien4', english: 'See you next time', tone: 4 }},
      { id: 'hk4-5', phrase: { chinese: '拜拜', romanization: 'bai4 bai4', english: 'Bye bye', tone: 4 }},
    ],
    quiz: [{ id: 'hkq4', type: 'listening', question: "'明旦見' means?", options: ['Goodbye', 'See you tomorrow', 'Take care', 'Bye'], correctIndex: 1 }],
    culturalNote: "'拜拜' is used by younger Hakka speakers!",
  },
  {
    id: 'hakka-u1-l5',
    dialect: 'hakka',
    unit: 1,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hkq5-1', type: 'listening', question: "'Hello' in Hakka?", options: ['再見', '你好', '多謝', '毋好'], correctIndex: 1 },
      { id: 'hkq5-2', type: 'listening', question: "'食吂?' means?", options: ['Thank you', 'Where going?', 'Have you eaten?', 'Goodbye'], correctIndex: 2 },
    ],
    culturalNote: "Great job completing Hakka Unit 1!",
  },

  // HAKKA UNIT 2: NUMBERS
  {
    id: 'hakka-u2-l1',
    dialect: 'hakka',
    unit: 2,
    lesson: 1,
    title: 'Numbers 1-10',
    subtitle: 'Basic counting',
    duration: '6 minutes • 10 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk5-1', phrase: { chinese: '一', romanization: 'iit5', english: 'One', tone: 5 }},
      { id: 'hk5-2', phrase: { chinese: '二', romanization: 'ngi4', english: 'Two', tone: 4 }},
      { id: 'hk5-3', phrase: { chinese: '三', romanization: 'sam1', english: 'Three', tone: 1 }},
      { id: 'hk5-4', phrase: { chinese: '四', romanization: 'si4', english: 'Four', tone: 4 }},
      { id: 'hk5-5', phrase: { chinese: '五', romanization: 'ng3', english: 'Five', tone: 3 }},
      { id: 'hk5-6', phrase: { chinese: '六', romanization: 'liu4', english: 'Six', tone: 4 }},
      { id: 'hk5-7', phrase: { chinese: '七', romanization: 'cit5', english: 'Seven', tone: 5 }},
      { id: 'hk5-8', phrase: { chinese: '八', romanization: 'bat5', english: 'Eight', tone: 5 }},
      { id: 'hk5-9', phrase: { chinese: '九', romanization: 'giu3', english: 'Nine', tone: 3 }},
      { id: 'hk5-10', phrase: { chinese: '十', romanization: 'sii2', english: 'Ten', tone: 2 }},
    ],
    quiz: [{ id: 'hkq6', type: 'listening', question: "'五' is what number?", options: ['3', '5', '7', '9'], correctIndex: 1 }],
    culturalNote: "Hakka tones differ from Mandarin - practice carefully!",
  },
  {
    id: 'hakka-u2-l2',
    dialect: 'hakka',
    unit: 2,
    lesson: 2,
    title: 'Numbers 11-100',
    subtitle: 'Higher numbers',
    duration: '6 minutes • 8 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk6-1', phrase: { chinese: '十一', romanization: 'sii2 iit5', english: 'Eleven', tone: 5 }},
      { id: 'hk6-2', phrase: { chinese: '二十', romanization: 'ngi4 sii2', english: 'Twenty', tone: 4 }},
      { id: 'hk6-3', phrase: { chinese: '二十五', romanization: 'ngi4 sii2 ng3', english: 'Twenty-five', tone: 3 }},
      { id: 'hk6-4', phrase: { chinese: '五十', romanization: 'ng3 sii2', english: 'Fifty', tone: 3 }},
      { id: 'hk6-5', phrase: { chinese: '一百', romanization: 'iit5 ba3', english: 'One hundred', tone: 3 }},
      { id: 'hk6-6', phrase: { chinese: '一千', romanization: 'iit5 cien1', english: 'One thousand', tone: 1 }},
    ],
    quiz: [{ id: 'hkq7', type: 'listening', question: "'一百' means?", options: ['Ten', 'One hundred', 'One thousand', 'Eleven'], correctIndex: 1 }],
    culturalNote: "Hakka compound numbers follow similar patterns!",
  },
  {
    id: 'hakka-u2-l3',
    dialect: 'hakka',
    unit: 2,
    lesson: 3,
    title: 'Prices & Money',
    subtitle: 'Shopping vocabulary',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk7-1', phrase: { chinese: '幾多錢?', romanization: 'gii3 do1 cien2?', english: 'How much?', tone: 2 }},
      { id: 'hk7-2', phrase: { chinese: '銀', romanization: 'ngiun4', english: 'Money', tone: 4 }},
      { id: 'hk7-3', phrase: { chinese: '貴', romanization: 'gui4', english: 'Expensive', tone: 4 }},
      { id: 'hk7-4', phrase: { chinese: '平', romanization: 'piang4', english: 'Cheap', tone: 4 }},
    ],
    quiz: [{ id: 'hkq8', type: 'listening', question: "Ask 'How much?'", options: ['幾多錢?', '貴', '平', '銀'], correctIndex: 0 }],
    culturalNote: "Hakka communities are found worldwide!",
  },
  {
    id: 'hakka-u2-l4',
    dialect: 'hakka',
    unit: 2,
    lesson: 4,
    title: 'Counting Items',
    subtitle: 'Measures and counters',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hk8-1', phrase: { chinese: '隻', romanization: 'zak5', english: 'Classifier (items)', tone: 5 }},
      { id: 'hk8-2', phrase: { chinese: '斤', romanization: 'gin1', english: 'Catty (500g)', tone: 1 }},
      { id: 'hk8-3', phrase: { chinese: '個', romanization: 'go4', english: 'Classifier', tone: 4 }},
      { id: 'hk8-4', phrase: { chinese: '件', romanization: 'kien4', english: 'Classifier (things)', tone: 4 }},
    ],
    quiz: [{ id: 'hkq9', type: 'listening', question: "Classifier for items?", options: ['隻', '斤', '個', '件'], correctIndex: 2 }],
    culturalNote: "Hakka classifiers help specify items!",
  },
  {
    id: 'hakka-u2-l5',
    dialect: 'hakka',
    unit: 2,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hkq10-1', type: 'listening', question: "'Twenty-five'?", options: ['二十五', '二十', '十五', '五十'], correctIndex: 0 },
      { id: 'hkq10-2', type: 'listening', question: "'平' means?", options: ['Expensive', 'Cheap', 'How much', 'Money'], correctIndex: 1 },
    ],
    culturalNote: "Hakka Unit 2 complete! You can now count and shop in Hakka!",
  },

  // HOKKIEN UNIT 4: FOOD & DRINKS
  {
    id: 'hokkien-u4-l1',
    dialect: 'hokkien',
    unit: 4,
    lesson: 1,
    title: 'Basic Foods',
    subtitle: 'Common food items',
    duration: '7 minutes • 8 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hf1-1', phrase: { chinese: '飯', romanization: 'pn̄g', english: 'Rice', tone: 7 }},
      { id: 'hf1-2', phrase: { chinese: '麵', romanization: 'mī', english: 'Noodles', tone: 7 }},
      { id: 'hf1-3', phrase: { chinese: '粥', romanization: 'chek', english: 'Rice porridge', tone: 4 }},
      { id: 'hf1-4', phrase: { chinese: '湯', romanization: 'thng', english: 'Soup', tone: 1 }},
      { id: 'hf1-5', phrase: { chinese: '菜', romanization: 'chhài', english: 'Vegetables', tone: 5 }},
      { id: 'hf1-6', phrase: { chinese: '肉', romanization: 'bah', english: 'Meat', tone: 4 }},
      { id: 'hf1-7', phrase: { chinese: '魚', romanization: 'hî', english: 'Fish', tone: 5 }},
      { id: 'hf1-8', phrase: { chinese: '雞', romanization: 'koe', english: 'Chicken', tone: 1 }},
    ],
    dialogue: { id: 'hfdl1', title: 'At a Restaurant', lines: [
      { speaker: 'A', chinese: '你要食啥?', romanization: 'lí-beh chia̤h siáⁿ?', english: 'What do you want to eat?' },
      { speaker: 'B', chinese: '我要一碗粥', romanization: 'góa-beh chiáⁿ chék', english: 'I want a bowl of porridge' },
    ]},
    quiz: [{ id: 'hfq1', type: 'listening', question: "'PN̄G' means?", options: ['Noodles', 'Rice', 'Soup', 'Vegetables'], correctIndex: 1 }],
    culturalNote: "Hokkien cuisine is famous in Singapore!",
  },
  {
    id: 'hokkien-u4-l2',
    dialect: 'hokkien',
    unit: 4,
    lesson: 2,
    title: 'Drinks',
    subtitle: 'Beverages',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hf2-1', phrase: { chinese: '水', romanization: 'chúi', english: 'Water', tone: 3 }},
      { id: 'hf2-2', phrase: { chinese: '茶', romanization: 'tê', english: 'Tea', tone: 5 }},
      { id: 'hf2-3', phrase: { chinese: '咖啡', romanization: 'ka-pi', english: 'Coffee', tone: 1 }},
      { id: 'hf2-4', phrase: { chinese: '牛奶', romanization: 'gû-ling', english: 'Milk', tone: 4 }},
      { id: 'hf2-5', phrase: { chinese: '果汁', romanization: 'kóe-chiap', english: 'Fruit juice', tone: 4 }},
      { id: 'hf2-6', phrase: { chinese: '汽水', romanization: 'khì-chúi', english: 'Soda', tone: 5 }},
    ],
    quiz: [{ id: 'hfq2', type: 'listening', question: "'TÊ' is?", options: ['Coffee', 'Tea', 'Water', 'Milk'], correctIndex: 1 }],
    culturalNote: "In Singapore, 'kopi' (coffee) is a must-try!",
  },
  {
    id: 'hokkien-u4-l3',
    dialect: 'hokkien',
    unit: 4,
    lesson: 3,
    title: 'Ordering Food',
    subtitle: 'How to order',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hf3-1', phrase: { chinese: '點餐', romanization: 'tiám-chhan', english: 'Order food', tone: 3 }},
      { id: 'hf3-2', phrase: { chinese: '买单', romanization: 'kâi-tan', english: 'Bill please', tone: 1 }},
      { id: 'hf3-3', phrase: { chinese: '打包', romanization: 'pá-tau', english: 'Takeaway', tone: 3 }},
      { id: 'hf3-4', phrase: { chinese: '好吃', romanization: 'hó-chia̤h', english: 'Delicious', tone: 4 }},
      { id: 'hf3-5', phrase: { chinese: '毋好食', romanization: 'm̄-hó-chia̤h', english: 'Not tasty', tone: 4 }},
    ],
    quiz: [{ id: 'hfq3', type: 'listening', question: "Ask for the bill?", options: ['點餐', '买单', '打包', '好吃'], correctIndex: 1 }],
    culturalNote: "Always say 'kâi-tan' when done eating!",
  },
  {
    id: 'hokkien-u4-l4',
    dialect: 'hokkien',
    unit: 4,
    lesson: 4,
    title: 'Hawker Food',
    subtitle: 'Singapore staples',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hf4-1', phrase: { chinese: '蝦麵', romanization: 'ê-mī', english: 'Prawn noodles', tone: 5 }},
      { id: 'hf4-2', phrase: { chinese: '肉骨茶', romanization: 'bah-kut-tê', english: 'Bone soup tea', tone: 5 }},
      { id: 'hf4-3', phrase: { chinese: '海南雞飯', romanization: 'hâi-lâm-ke-pn̄g', english: 'Chicken rice', tone: 5 }},
      { id: 'hf4-4', phrase: { chinese: '沙嗲', romanization: 'sa-tiám', english: 'Satay', tone: 3 }},
    ],
    quiz: [{ id: 'hfq4', type: 'listening', question: "'BAH-KUT-TE' is?", options: ['Chicken rice', 'Prawn noodles', 'Bone soup tea', 'Satay'], correctIndex: 2 }],
    culturalNote: "Singapore hawker culture is UNESCO recognized!",
  },
  {
    id: 'hokkien-u4-l5',
    dialect: 'hokkien',
    unit: 4,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hfq5-1', type: 'listening', question: "'Rice' in Hokkien?", options: ['麵', '飯', '粥', '菜'], correctIndex: 1 },
      { id: 'hfq5-2', type: 'listening', question: "Ask for bill?", options: ['點餐', '打包', '买单', '好吃'], correctIndex: 2 },
    ],
    culturalNote: "Great job! Now you can order food in Hokkien!",
  },

  // HOKKIEN UNIT 5: TRAVEL & DIRECTIONS
  {
    id: 'hokkien-u5-l1',
    dialect: 'hokkien',
    unit: 5,
    lesson: 1,
    title: 'Transportation',
    subtitle: 'Getting around',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ht1-1', phrase: { chinese: '車', romanization: 'chhia', english: 'Car/Vehicle', tone: 1 }},
      { id: 'ht1-2', phrase: { chinese: '火車', romanization: 'hóe-chhia', english: 'Train', tone: 1 }},
      { id: 'ht1-3', phrase: { chinese: '巴士', romanization: 'pa-suh', english: 'Bus', tone: 1 }},
      { id: 'ht1-4', phrase: { chinese: '捷運', romanization: 'chiáh-ūn', english: 'MRT/Subway', tone: 7 }},
      { id: 'ht1-5', phrase: { chinese: '計程車', romanization: 'kè-thêng-chhia', english: 'Taxi', tone: 5 }},
    ],
    quiz: [{ id: 'htq1', type: 'listening', question: "'MRT' in Hokkien?", options: ['車', '火車', '捷運', '巴士'], correctIndex: 2 }],
    culturalNote: "Singapore's MRT is efficient and easy to use!",
  },
  {
    id: 'hokkien-u5-l2',
    dialect: 'hokkien',
    unit: 5,
    lesson: 2,
    title: 'Directions',
    subtitle: 'Where is it?',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ht2-1', phrase: { chinese: '叨位?', romanization: 'to-ūi?', english: 'Where?', tone: 5 }},
      { id: 'ht2-2', phrase: { chinese: '左邊', romanization: 'chó-piⁿ', english: 'Left', tone: 1 }},
      { id: 'ht2-3', phrase: { chinese: '右邊', romanization: 'iū-piⁿ', english: 'Right', tone: 7 }},
      { id: 'ht2-4', phrase: { chinese: '前面', romanization: 'chêng-bīn', english: 'Front', tone: 5 }},
      { id: 'ht2-5', phrase: { chinese: '後壁', romanization: 'āu-piah', english: 'Back', tone: 7 }},
    ],
    quiz: [{ id: 'htq2', type: 'listening', question: "'Left' in Hokkien?", options: ['右邊', '左邊', '前面', '後壁'], correctIndex: 1 }],
    culturalNote: "Pointing with your whole hand is common in Singapore!",
  },
  {
    id: 'hokkien-u5-l3',
    dialect: 'hokkien',
    unit: 5,
    lesson: 3,
    title: 'Places',
    subtitle: 'Common locations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ht3-1', phrase: { chinese: '車站', romanization: 'chhia-chām', english: 'Station', tone: 6 }},
      { id: 'ht3-2', phrase: { chinese: '機場', romanization: 'kee-tiûⁿ', english: 'Airport', tone: 5 }},
      { id: 'ht3-3', phrase: { chinese: '酒店', romanization: 'chiú-tiàm', english: 'Hotel', tone: 5 }},
      { id: 'ht3-4', phrase: { chinese: '醫院', romanization: 'ī-Īⁿ', english: 'Hospital', tone: 1 }},
    ],
    quiz: [{ id: 'htq3', type: 'listening', question: "'Station' in Hokkien?", options: ['車站', '機場', '酒店', '醫院'], correctIndex: 0 }],
    culturalNote: "Singapore has many beautiful parks to explore!",
  },
  {
    id: 'hokkien-u5-l4',
    dialect: 'hokkien',
    unit: 5,
    lesson: 4,
    title: 'Asking for Help',
    subtitle: 'Getting assistance',
    duration: '6 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ht4-1', phrase: { chinese: '請問', romanization: 'chhiáⁿ-mn̄g', english: 'May I ask', tone: 3 }},
      { id: 'ht4-2', phrase: { chinese: '的多遠?', romanization: 'toā-chōa?', english: 'How far?', tone: 5 }},
      { id: 'ht4-3', phrase: { chinese: '我欲去...', romanization: 'góa-beh-khì...', english: 'I want to go to...', tone: 3 }},
    ],
    quiz: [{ id: 'htq4', type: 'listening', question: "'May I ask'?", options: ['請問', '的多遠', '欲去叨位', '會使嘸'], correctIndex: 0 }],
    culturalNote: "Singaporeans are helpful - don't be shy to ask!",
  },
  {
    id: 'hokkien-u5-l5',
    dialect: 'hokkien',
    unit: 5,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'htq5-1', type: 'listening', question: "'MRT' in Hokkien?", options: ['巴士', '捷運', '火車', '計程車'], correctIndex: 1 },
      { id: 'htq5-2', type: 'listening', question: "'Where'?", options: ['叨位', '左邊', '右邊', '前面'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now get around in Hokkien!",
  },

  // CANTONESE UNIT 3: FOOD & DRINKS
  {
    id: 'cantonese-u3-l1',
    dialect: 'cantonese',
    unit: 3,
    lesson: 1,
    title: 'Basic Foods',
    subtitle: 'Common food items',
    duration: '7 minutes • 8 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cf1-1', phrase: { chinese: '飯', romanization: 'faan6', english: 'Rice', tone: 6 }},
      { id: 'cf1-2', phrase: { chinese: '麵', romanization: 'min6', english: 'Noodles', tone: 6 }},
      { id: 'cf1-3', phrase: { chinese: '粥', romanization: 'zuk1', english: 'Rice porridge', tone: 1 }},
      { id: 'cf1-4', phrase: { chinese: '湯', romanization: 'tong1', english: 'Soup', tone: 1 }},
      { id: 'cf1-5', phrase: { chinese: '菜', romanization: 'coi3', english: 'Vegetables', tone: 3 }},
      { id: 'cf1-6', phrase: { chinese: '肉', romanization: 'juk6', english: 'Meat', tone: 6 }},
      { id: 'cf1-7', phrase: { chinese: '魚', romanization: 'yu4', english: 'Fish', tone: 4 }},
      { id: 'cf1-8', phrase: { chinese: '雞', romanization: 'gai1', english: 'Chicken', tone: 1 }},
    ],
    dialogue: { id: 'cfdl1', title: 'At a Restaurant', lines: [
      { speaker: 'A', chinese: '你想食啲咩?', romanization: 'nei5 soeng2 sik6 di1 me1?', english: 'What do you want to eat?' },
      { speaker: 'B', chinese: '我要一碗粥', romanization: 'ngo5 yiu3 jat1 wan2 zuk1', english: 'I want a bowl of porridge' },
    ]},
    quiz: [{ id: 'cfq1', type: 'listening', question: "'FAAN6' means?", options: ['Noodles', 'Rice', 'Soup', 'Vegetables'], correctIndex: 1 }],
    culturalNote: "Cantonese cuisine is world-famous for dim sum!",
  },
  {
    id: 'cantonese-u3-l2',
    dialect: 'cantonese',
    unit: 3,
    lesson: 2,
    title: 'Drinks',
    subtitle: 'Beverages',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cf2-1', phrase: { chinese: '水', romanization: 'seoi2', english: 'Water', tone: 2 }},
      { id: 'cf2-2', phrase: { chinese: '茶', romanization: 'caa4', english: 'Tea', tone: 4 }},
      { id: 'cf2-3', phrase: { chinese: '咖啡', romanization: 'gaa3 fe1', english: 'Coffee', tone: 3 }},
      { id: 'cf2-4', phrase: { chinese: '牛奶', romanization: 'ngau4 naai5', english: 'Milk', tone: 4 }},
      { id: 'cf2-5', phrase: { chinese: '奶茶', romanization: 'naai5 caa4', english: 'Milk tea', tone: 4 }},
    ],
    quiz: [{ id: 'cfq2', type: 'listening', question: "'CAA4' is?", options: ['Coffee', 'Tea', 'Water', 'Milk'], correctIndex: 1 }],
    culturalNote: "Dim sum and yum cha is a beloved Cantonese tradition!",
  },
  {
    id: 'cantonese-u3-l3',
    dialect: 'cantonese',
    unit: 3,
    lesson: 3,
    title: 'Ordering Food',
    subtitle: 'How to order',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cf3-1', phrase: { chinese: '點餐', romanization: 'dim2 caan1', english: 'Order food', tone: 2 }},
      { id: 'cf3-2', phrase: { chinese: '埋單', romanization: 'maai4 daan1', english: 'Bill please', tone: 4 }},
      { id: 'cf3-3', phrase: { chinese: '外賣', romanization: 'ngoi6 maai6', english: 'Takeaway', tone: 6 }},
      { id: 'cf3-4', phrase: { chinese: '好味', romanization: 'hou2 mei6', english: 'Delicious', tone: 2 }},
    ],
    quiz: [{ id: 'cfq3', type: 'listening', question: "Ask for the bill?", options: ['點餐', '埋單', '外賣', '好味'], correctIndex: 1 }],
    culturalNote: "Say 'maai4 daan1' when done eating!",
  },
  {
    id: 'cantonese-u3-l4',
    dialect: 'cantonese',
    unit: 3,
    lesson: 4,
    title: 'Hong Kong Foods',
    subtitle: 'Local specialties',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cf4-1', phrase: { chinese: '雲吞', romanization: 'wan4 tan1', english: 'Wonton', tone: 4 }},
      { id: 'cf4-2', phrase: { chinese: '叉燒', romanization: 'caa1 siu1', english: 'BBQ pork', tone: 1 }},
      { id: 'cf4-3', phrase: { chinese: '蛋撻', romanization: 'daan6 taat3', english: 'Egg tart', tone: 6 }},
      { id: 'cf4-4', phrase: { chinese: '菠蘿包', romanization: 'bo1 lo4 baau1', english: 'Pineapple bun', tone: 1 }},
    ],
    quiz: [{ id: 'cfq4', type: 'listening', question: "'Wonton' in Cantonese?", options: ['叉燒', '雲吞', '蛋撻', '菠蘿包'], correctIndex: 1 }],
    culturalNote: "Hong Kong has amazing street food!",
  },
  {
    id: 'cantonese-u3-l5',
    dialect: 'cantonese',
    unit: 3,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'cfq5-1', type: 'listening', question: "'Rice' in Cantonese?", options: ['麵', '飯', '粥', '湯'], correctIndex: 1 },
      { id: 'cfq5-2', type: 'listening', question: "Ask for bill?", options: ['點餐', '埋單', '外賣', '好味'], correctIndex: 1 },
    ],
    culturalNote: "Great job! Now you can order food in Cantonese!",
  },

  // CANTONESE UNIT 4: TRAVEL & DIRECTIONS
  {
    id: 'cantonese-u4-l1',
    dialect: 'cantonese',
    unit: 4,
    lesson: 1,
    title: 'Transportation',
    subtitle: 'Getting around',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ct1-1', phrase: { chinese: '車', romanization: 'ce1', english: 'Car/Vehicle', tone: 1 }},
      { id: 'ct1-2', phrase: { chinese: '火車', romanization: 'fo2 ce1', english: 'Train', tone: 2 }},
      { id: 'ct1-3', phrase: { chinese: '巴士', romanization: 'baa1 si6', english: 'Bus', tone: 1 }},
      { id: 'ct1-4', phrase: { chinese: '地鐵', romanization: 'dei6 tit3', english: 'MTR/Subway', tone: 3 }},
      { id: 'ct1-5', phrase: { chinese: '的士', romanization: 'di1 si2', english: 'Taxi', tone: 1 }},
    ],
    quiz: [{ id: 'ctq1', type: 'listening', question: "'MTR' in Cantonese?", options: ['車', '火車', '地鐵', '巴士'], correctIndex: 2 }],
    culturalNote: "Hong Kong's MTR is fast and efficient!",
  },
  {
    id: 'cantonese-u4-l2',
    dialect: 'cantonese',
    unit: 4,
    lesson: 2,
    title: 'Directions',
    subtitle: 'Where is it?',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ct2-1', phrase: { chinese: '邊度?', romanization: 'bin1 dou6?', english: 'Where?', tone: 1 }},
      { id: 'ct2-2', phrase: { chinese: '左邊', romanization: 'zo2 bin1', english: 'Left', tone: 2 }},
      { id: 'ct2-3', phrase: { chinese: '右邊', romanization: 'jau6 bin1', english: 'Right', tone: 6 }},
      { id: 'ct2-4', phrase: { chinese: '前面', romanization: 'cin4 min6', english: 'Front', tone: 4 }},
      { id: 'ct2-5', phrase: { chinese: '後面', romanization: 'hau6 min6', english: 'Back', tone: 6 }},
    ],
    quiz: [{ id: 'ctq2', type: 'listening', question: "'Left' in Cantonese?", options: ['右邊', '左邊', '前面', '後面'], correctIndex: 1 }],
    culturalNote: "Hong Kong is compact and easy to navigate!",
  },
  {
    id: 'cantonese-u4-l3',
    dialect: 'cantonese',
    unit: 4,
    lesson: 3,
    title: 'Places',
    subtitle: 'Common locations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ct3-1', phrase: { chinese: '車站', romanization: 'ce1 zaam6', english: 'Station', tone: 6 }},
      { id: 'ct3-2', phrase: { chinese: '機場', romanization: 'gei1 coeng4', english: 'Airport', tone: 4 }},
      { id: 'ct3-3', phrase: { chinese: '酒店', romanization: 'zau2 dim3', english: 'Hotel', tone: 3 }},
      { id: 'ct3-4', phrase: { chinese: '醫院', romanization: 'ji1 jyun2', english: 'Hospital', tone: 4 }},
    ],
    quiz: [{ id: 'ctq3', type: 'listening', question: "'Station' in Cantonese?", options: ['車站', '機場', '酒店', '醫院'], correctIndex: 0 }],
    culturalNote: "Hong Kong has amazing malls and parks!",
  },
  {
    id: 'cantonese-u4-l4',
    dialect: 'cantonese',
    unit: 4,
    lesson: 4,
    title: 'Asking for Help',
    subtitle: 'Getting assistance',
    duration: '6 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'ct4-1', phrase: { chinese: '請問', romanization: 'ceng2 man6', english: 'May I ask', tone: 2 }},
      { id: 'ct4-2', phrase: { chinese: '幾遠?', romanization: 'gei2 jyun5?', english: 'How far?', tone: 2 }},
      { id: 'ct4-3', phrase: { chinese: '你去邊?', romanization: 'nei5 heoi3 bin1?', english: 'Where are you going?', tone: 1 }},
    ],
    quiz: [{ id: 'ctq4', type: 'listening', question: "'May I ask'?", options: ['請問', '幾遠', '你去邊', '得唔得'], correctIndex: 0 }],
    culturalNote: "Hong Kongers are helpful - ask away!",
  },
  {
    id: 'cantonese-u4-l5',
    dialect: 'cantonese',
    unit: 4,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'ctq5-1', type: 'listening', question: "'MTR' in Cantonese?", options: ['巴士', '地鐵', '火車', '的士'], correctIndex: 1 },
      { id: 'ctq5-2', type: 'listening', question: "'Where'?", options: ['邊度', '左邊', '右邊', '前面'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now get around in Cantonese!",
  },

  // HAKKA UNIT 3: FOOD & DRINKS
  {
    id: 'hakka-u3-l1',
    dialect: 'hakka',
    unit: 3,
    lesson: 1,
    title: 'Basic Foods',
    subtitle: 'Common food items',
    duration: '7 minutes • 8 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkf1-1', phrase: { chinese: '飯', romanization: 'pon4', english: 'Rice', tone: 4 }},
      { id: 'hkf1-2', phrase: { chinese: '麵', romanization: 'mien4', english: 'Noodles', tone: 4 }},
      { id: 'hkf1-3', phrase: { chinese: '粥', romanization: 'chuk5', english: 'Rice porridge', tone: 5 }},
      { id: 'hkf1-4', phrase: { chinese: '湯', romanization: 'tong1', english: 'Soup', tone: 1 }},
      { id: 'hkf1-5', phrase: { chinese: '菜', romanization: 'coi4', english: 'Vegetables', tone: 4 }},
      { id: 'hkf1-6', phrase: { chinese: '肉', romanization: 'ngiuk5', english: 'Meat', tone: 5 }},
      { id: 'hkf1-7', phrase: { chinese: '魚', romanization: 'ng2', english: 'Fish', tone: 2 }},
      { id: 'hkf1-8', phrase: { chinese: '雞', romanization: 'gai1', english: 'Chicken', tone: 1 }},
    ],
    dialogue: { id: 'hkfdl1', title: 'At a Restaurant', lines: [
      { speaker: 'A', chinese: '你想食麼?', romanization: 'ngi5 xiong4 xit5 ma1?', english: 'What do you want to eat?' },
      { speaker: 'B', chinese: '我要一碗粥', romanization: 'ngai4 yiu4 yit5 von3 chuk5', english: 'I want a bowl of porridge' },
    ]},
    quiz: [{ id: 'hkfq1', type: 'listening', question: "'PON4' means?", options: ['Noodles', 'Rice', 'Soup', 'Vegetables'], correctIndex: 1 }],
    culturalNote: "Hakka cuisine is known for salt-baked chicken!",
  },
  {
    id: 'hakka-u3-l2',
    dialect: 'hakka',
    unit: 3,
    lesson: 2,
    title: 'Drinks',
    subtitle: 'Beverages',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkf2-1', phrase: { chinese: '水', romanization: 'shui3', english: 'Water', tone: 3 }},
      { id: 'hkf2-2', phrase: { chinese: '茶', romanization: 'ca2', english: 'Tea', tone: 2 }},
      { id: 'hkf2-3', phrase: { chinese: '咖啡', romanization: 'ga3 fi1', english: 'Coffee', tone: 1 }},
      { id: 'hkf2-4', phrase: { chinese: '牛奶', romanization: 'ngiu2 nai3', english: 'Milk', tone: 3 }},
      { id: 'hkf2-5', phrase: { chinese: '果汁', romanization: 'gwo3 zhib5', english: 'Fruit juice', tone: 5 }},
    ],
    quiz: [{ id: 'hkfq2', type: 'listening', question: "What is 'CA2'?", options: ['Coffee', 'Tea', 'Water', 'Milk'], correctIndex: 1 }],
    culturalNote: "Hakka communities love their tea!",
  },
  {
    id: 'hakka-u3-l3',
    dialect: 'hakka',
    unit: 3,
    lesson: 3,
    title: 'Ordering Food',
    subtitle: 'How to order',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkf3-1', phrase: { chinese: '點菜', romanization: 'diam3 coi4', english: 'Order food', tone: 3 }},
      { id: 'hkf3-2', phrase: { chinese: '埋單', romanization: 'mai4 dan1', english: 'Bill please', tone: 4 }},
      { id: 'hkf3-3', phrase: { chinese: '打包', romanization: 'da3 bau1', english: 'Takeaway', tone: 3 }},
      { id: 'hkf3-4', phrase: { chinese: '好食', romanization: 'ho3 xit5', english: 'Delicious', tone: 5 }},
    ],
    quiz: [{ id: 'hkfq3', type: 'listening', question: "Ask for the bill?", options: ['點菜', '埋單', '打包', '好食'], correctIndex: 1 }],
    culturalNote: "Say 'mai4 dan1' when done eating!",
  },
  {
    id: 'hakka-u3-l4',
    dialect: 'hakka',
    unit: 3,
    lesson: 4,
    title: 'Hakka Foods',
    subtitle: 'Traditional dishes',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkf4-1', phrase: { chinese: '鹽焗雞', romanization: 'yam2 guk5 gai1', english: 'Salt-baked chicken', tone: 5 }},
      { id: 'hkf4-2', phrase: { chinese: '梅菜扣肉', romanization: 'mui2 coi4 kiu4 ngiuk5', english: 'Pork with preserved veg', tone: 4 }},
      { id: 'hkf4-3', phrase: { chinese: '客家粄', romanization: 'hak5 ga1 ban3', english: 'Hakka rice cake', tone: 3 }},
      { id: 'hkf4-4', phrase: { chinese: '酿豆腐', romanization: 'ngiong4 tau4 fu3', english: 'Stuffed tofu', tone: 3 }},
    ],
    quiz: [{ id: 'hkfq4', type: 'listening', question: "What is 'Salt-baked chicken' in Hakka?", options: ['鹽焗雞', '梅菜扣肉', '客家粄', '酿豆腐'], correctIndex: 0 }],
    culturalNote: "Hakka cuisine is famous throughout Asia!",
  },
  {
    id: 'hakka-u3-l5',
    dialect: 'hakka',
    unit: 3,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hkfq5-1', type: 'listening', question: "'Rice' in Hakka?", options: ['麵', '飯', '粥', '菜'], correctIndex: 1 },
      { id: 'hkfq5-2', type: 'listening', question: "Ask for bill?", options: ['點菜', '埋單', '打包', '好食'], correctIndex: 1 },
    ],
    culturalNote: "Great job! Now you can order food in Hakka!",
  },

  // HAKKA UNIT 4: TRAVEL & DIRECTIONS
  {
    id: 'hakka-u4-l1',
    dialect: 'hakka',
    unit: 4,
    lesson: 1,
    title: 'Transportation',
    subtitle: 'Getting around',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt1-1', phrase: { chinese: '車', romanization: 'cha1', english: 'Car/Vehicle', tone: 1 }},
      { id: 'hkt1-2', phrase: { chinese: '火車', romanization: 'fo2 cha1', english: 'Train', tone: 2 }},
      { id: 'hkt1-3', phrase: { chinese: '巴士', romanization: 'ba1 sii4', english: 'Bus', tone: 4 }},
      { id: 'hkt1-4', phrase: { chinese: '高鐵', romanization: 'goo1 tiet3', english: 'High-speed rail', tone: 3 }},
    ],
    quiz: [{ id: 'hktq1', type: 'listening', question: "'Bus' in Hakka?", options: ['車', '火車', '巴士', '高鐵'], correctIndex: 2 }],
    culturalNote: "Taiwan's High Speed Rail is fast and convenient!",
  },
  {
    id: 'hakka-u4-l2',
    dialect: 'hakka',
    unit: 4,
    lesson: 2,
    title: 'Directions',
    subtitle: 'Where is it?',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt2-1', phrase: { chinese: '哪位?', romanization: 'nai5 vi6?', english: 'Where?', tone: 4 }},
      { id: 'hkt2-2', phrase: { chinese: '左片', romanization: 'zo3 pian4', english: 'Left', tone: 3 }},
      { id: 'hkt2-3', phrase: { chinese: '右片', romanization: 'iu3 pian4', english: 'Right', tone: 3 }},
      { id: 'hkt2-4', phrase: { chinese: '前片', romanization: 'cien4 pian4', english: 'Front', tone: 4 }},
      { id: 'hkt2-5', phrase: { chinese: '後片', romanization: 'heu4 pian4', english: 'Back', tone: 4 }},
    ],
    quiz: [{ id: 'hktq2', type: 'listening', question: "'Left' in Hakka?", options: ['右片', '左片', '前片', '後片'], correctIndex: 1 }],
    culturalNote: "Taiwan is easy to navigate!",
  },
  {
    id: 'hakka-u4-l3',
    dialect: 'hakka',
    unit: 4,
    lesson: 3,
    title: 'Places',
    subtitle: 'Common locations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt3-1', phrase: { chinese: '車站', romanization: 'cha1 zam4', english: 'Station', tone: 4 }},
      { id: 'hkt3-2', phrase: { chinese: '機場', romanization: 'gi1 cong2', english: 'Airport', tone: 2 }},
      { id: 'hkt3-3', phrase: { chinese: '酒店', romanization: 'ziu3 diam4', english: 'Hotel', tone: 4 }},
      { id: 'hkt3-4', phrase: { chinese: '醫院', romanization: 'i1 ian4', english: 'Hospital', tone: 4 }},
    ],
    quiz: [{ id: 'hktq3', type: 'listening', question: "'Station' in Hakka?", options: ['車站', '機場', '酒店', '醫院'], correctIndex: 0 }],
    culturalNote: "Taiwan has great public transportation!",
  },
  {
    id: 'hakka-u4-l4',
    dialect: 'hakka',
    unit: 4,
    lesson: 4,
    title: 'Asking for Help',
    subtitle: 'Getting assistance',
    duration: '6 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt4-1', phrase: { chinese: '請問', romanization: 'cian3 mun4', english: 'May I ask', tone: 3 }},
      { id: 'hkt4-2', phrase: { chinese: '幾遠?', romanization: 'gi3 ian5?', english: 'How far?', tone: 3 }},
      { id: 'hkt4-3', phrase: { chinese: '我去...', romanization: 'ngai4 hi4...', english: 'I go to...', tone: 4 }},
    ],
    quiz: [{ id: 'hktq4', type: 'listening', question: "'May I ask'?", options: ['請問', '幾遠', '哪位', '我去'], correctIndex: 0 }],
    culturalNote: "Taiwanese are very helpful!",
  },
  {
    id: 'hakka-u4-l5',
    dialect: 'hakka',
    unit: 4,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hktq5-1', type: 'listening', question: "'Bus' in Hakka?", options: ['車', '火車', '巴士', '高鐵'], correctIndex: 2 },
      { id: 'hktq5-2', type: 'listening', question: "'Where'?", options: ['哪位', '左片', '右片', '前片'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now get around in Hakka!",
  },
  // NEW: Hokkien Unit 6 - Emotions
  {
    id: 'hokkien-u6-l1',
    dialect: 'hokkien',
    unit: 6,
    lesson: 1,
    title: 'Happy & Sad',
    subtitle: 'Expressing emotions',
    duration: '6 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hke1-1', phrase: { chinese: '歡喜', romanization: 'hoaⁿ-hí', english: 'Happy', tone: 1 }},
      { id: 'hke1-2', phrase: { chinese: '憂愁', romanization: 'iu-chhiû', english: 'Sad', tone: 5 }},
      { id: 'hke1-3', phrase: { chinese: '愁', romanization: 'shiû', english: 'Worried', tone: 5 }},
      { id: 'hke1-4', phrase: { chinese: '生氣', romanization: 'seⁿ-khì', english: 'Angry', tone: 3 }},
      { id: 'hke1-5', phrase: { chinese: '驚', romanization: 'kiaⁿ', english: 'Scared', tone: 1 }},
      { id: 'hke1-6', phrase: { chinese: 'lín', romanization: 'lín', english: 'Tired', tone: 5 }},
      { id: 'hke1-7', phrase: { chinese: '無爽快', romanization: 'bô-sóng-khoài', english: 'Uncomfortable', tone: 7 }},
    ],
    dialogue: {
      id: 'hke1-d',
      title: 'At the Market',
      lines: [
        { speaker: 'A', chinese: '今日你hoaⁿ-hí喔!', romanization: 'kin-a-jit lí hoaⁿ-hí--ooh', english: 'You look happy today!' },
        { speaker: 'B', chinese: '因為我中獎啊!', romanization: 'in-ūi tiong-chiú--ah', english: 'Because I won a prize!' },
        { speaker: 'A', chinese: '真好!', romanization: 'chin-hó', english: 'Great!' },
      ]
    },
    quiz: [
      { id: 'hkeq1-1', type: 'listening', question: "What is 'Happy' in Hokkien?", options: ['歡喜', 'sad', '愁', '氣'], correctIndex: 0 },
      { id: 'hkeq1-2', type: 'listening', question: "What is 'Angry'?", options: ['驚', '氣', '愁', 'lín'], correctIndex: 1 },
    ],
    culturalNote: "Hokkien expressions often use reduplication for emphasis!",
  },
  {
    id: 'hokkien-u6-l2',
    dialect: 'hokkien',
    unit: 6,
    lesson: 2,
    title: 'Surprised & Excited',
    subtitle: 'Strong emotions',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hke2-1', phrase: { chinese: '趣味', romanization: 'chù-bī', english: 'Interesting/Fun', tone: 3 }},
      { id: 'hke2-2', phrase: { chinese: '讚', romanization: 'chián', english: 'Amazing', tone: 5 }},
      { id: 'hke2-3', phrase: { chinese: '見笑', romanization: 'kiàn-siáu', english: 'Embarrassed', tone: 3 }},
      { id: 'hke2-4', phrase: { chinese: '厭', romanization: 'iam', english: 'Disgusted', tone: 7 }},
      { id: 'hke2-5', phrase: { chinese: '无聊', romanization: 'bô-liau', english: 'Bored', tone: 5 }},
      { id: 'hke2-6', phrase: { chinese: '期待', romanization: 'kî-tāi', english: 'Excited', tone: 5 }},
    ],
    quiz: [
      { id: 'hkeq2-1', type: 'listening', question: "What is 'Bored'?", options: ['趣味', '无聊', '見笑', '厭'], correctIndex: 1 },
      { id: 'hkeq2-2', type: 'listening', question: "What is 'Excited'?", options: ['期待', '讚', '趣味', '見笑'], correctIndex: 0 },
    ],
    culturalNote: "Hokkien has many compound words for emotions!",
  },
  {
    id: 'hokkien-u6-l3',
    dialect: 'hokkien',
    unit: 6,
    lesson: 3,
    title: 'Loving & Hating',
    subtitle: 'Strong feelings',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hke3-1', phrase: { chinese: '愛', romanization: 'ài', english: 'Love', tone: 3 }},
      { id: 'hke3-2', phrase: { chinese: '怨恨', romanization: 'uàn-hūn', english: 'Hate', tone: 7 }},
      { id: 'hke3-3', phrase: { chinese: '思念', romanization: 'sū-liām', english: 'Miss (someone)', tone: 3 }},
      { id: 'hke3-4', phrase: { chinese: '感謝', romanization: 'kám-siā', english: 'Grateful', tone: 3 }},
      { id: 'hke3-5', phrase: { chinese: '對不起', romanization: 'tuì-put-kí', english: 'Sorry', tone: 5 }},
      { id: 'hke3-6', phrase: { chinese: '原諒', romanization: 'guân-liāng', english: 'Forgive', tone: 5 }},
    ],
    quiz: [
      { id: 'hkeq3-1', type: 'listening', question: "What is 'Love'?", options: ['愛', '怨恨', '思念', '感謝'], correctIndex: 0 },
      { id: 'hkeq3-2', type: 'listening', question: "What is 'Sorry'?", options: ['感謝', '對不起', '原諒', '思念'], correctIndex: 1 },
    ],
    culturalNote: "Respect and emotion terms are very important in Hokkien culture!",
  },
  {
    id: 'hokkien-u6-l4',
    dialect: 'hokkien',
    unit: 6,
    lesson: 4,
    title: 'Feelings & Health',
    subtitle: 'Physical sensations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hke4-1', phrase: { chinese: '感冒', romanization: 'kám-mōa', english: 'Sick/Cold', tone: 3 }},
      { id: 'hke4-2', phrase: { chinese: '頭疼', romanization: 'thâu-thiànn', english: 'Headache', tone: 5 }},
      { id: 'hke4-3', phrase: { chinese: '肚疼', romanization: 'tōu-thiànn', english: 'Stomachache', tone: 5 }},
      { id: 'hke4-4', phrase: { chinese: '枵', romanization: 'iau', english: 'Hungry', tone: 5 }},
      { id: 'hke4-5', phrase: { chinese: '飽', romanization: 'pá', english: 'Full (ate)', tone: 2 }},
      { id: 'hke4-6', phrase: { chinese: '想睏', romanization: 'siūⁿ-kùn', english: 'Sleepy', tone: 3 }},
    ],
    quiz: [
      { id: 'hkeq4-1', type: 'listening', question: "What is 'Sick'?", options: ['感冒', '頭疼', '肚疼', '想睏'], correctIndex: 0 },
      { id: 'hkeq4-2', type: 'listening', question: "What is 'Sleepy'?", options: ['飽', '想睏', '肚子腹', '頭疼'], correctIndex: 1 },
    ],
    culturalNote: "In Hokkien, 'chia̤h-bē-bē' (have you eaten?) is a common greeting!",
  },
  {
    id: 'hokkien-u6-l5',
    dialect: 'hokkien',
    unit: 6,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hkeq5-1', type: 'listening', question: "What is 'Happy' in Hokkien?", options: ['歡喜', 'sad', '氣', '驚'], correctIndex: 0 },
      { id: 'hkeq5-2', type: 'listening', question: "What is 'Love'?", options: ['怨恨', '愛', '思念', '感謝'], correctIndex: 1 },
      { id: 'hkeq5-3', type: 'listening', question: "What is 'Sick'?", options: ['感冒', '頭疼', '肚疼', '想睏'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now express many emotions in Hokkien!",
  },
  // NEW: Cantonese Unit 5 - Emotions
  {
    id: 'cantonese-u5-l1',
    dialect: 'cantonese',
    unit: 5,
    lesson: 1,
    title: 'Happy & Sad',
    subtitle: 'Expressing emotions',
    duration: '6 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cne1-1', phrase: { chinese: '開心', romanization: 'hoi1 sam1', english: 'Happy', tone: 1 }},
      { id: 'cne1-2', phrase: { chinese: '傷心', romanization: 'soeng1 sam1', english: 'Sad', tone: 1 }},
      { id: 'cne1-3', phrase: { chinese: '擔心', romanization: 'daam1 sam1', english: 'Worried', tone: 1 }},
      { id: 'cne1-4', phrase: { chinese: '嬲', romanization: 'nau6', english: 'Angry', tone: 6 }},
      { id: 'cne1-5', phrase: { chinese: '驚', romanization: 'geng1', english: 'Scared', tone: 1 }},
      { id: 'cne1-6', phrase: { chinese: '攰', romanization: 'gui6', english: 'Tired', tone: 6 }},
      { id: 'cne1-7', phrase: { chinese: '唔舒服', romanization: 'm4 syu1 fuk6', english: 'Uncomfortable', tone: 4 }},
    ],
    dialogue: {
      id: 'cne1-d',
      title: 'At the Tea Restaurant',
      lines: [
        { speaker: 'A', chinese: '你今日好開心喎!', romanization: 'nei5 gam1 jat6 hou2 hoi1 sam1 wo3', english: 'You look happy today!' },
        { speaker: 'B', chinese: '係呀，我升職喇!', romanization: 'hai6 aa3, ngo5 sing1 zik6 laa3', english: 'Yes, I got promoted!' },
        { speaker: 'A', chinese: '恭喜恭喜!', romanization: 'gung1 hei2 gung1 hei2', english: 'Congratulations!' },
      ]
    },
    quiz: [
      { id: 'cneq1-1', type: 'listening', question: "What is 'Happy' in Cantonese?", options: ['開心', '傷心', '擔心', '嬲'], correctIndex: 0 },
      { id: 'cneq1-2', type: 'listening', question: "What is 'Sad'?", options: ['開心', '傷心', '擔心', '驚'], correctIndex: 1 },
    ],
    culturalNote: "Cantonese uses 'sam1' (heart) in many emotion words!",
  },
  {
    id: 'cantonese-u5-l2',
    dialect: 'cantonese',
    unit: 5,
    lesson: 2,
    title: 'Surprised & Excited',
    subtitle: 'Strong emotions',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cne2-1', phrase: { chinese: '有趣', romanization: 'jau5 ceoi3', english: 'Interesting', tone: 5 }},
      { id: 'cne2-2', phrase: { chinese: '勁', romanization: 'ging6', english: 'Amazing', tone: 6 }},
      { id: 'cne2-3', phrase: { chinese: '尴尬', romanization: 'gaa1 gaa3', english: 'Embarrassed', tone: 1 }},
      { id: 'cne2-4', phrase: { chinese: '嘔心', romanization: 'au3 sam1', english: 'Disgusted', tone: 2 }},
      { id: 'cne2-5', phrase: { chinese: '悶', romanization: 'mun6', english: 'Bored', tone: 6 }},
      { id: 'cne2-6', phrase: { chinese: '期待', romanization: 'kei1 daai6', english: 'Excited', tone: 4 }},
    ],
    quiz: [
      { id: 'cneq2-1', type: 'listening', question: "What is 'Bored'?", options: ['有趣', '悶', '尴尬', '嘔心'], correctIndex: 1 },
      { id: 'cneq2-2', type: 'listening', question: "What is 'Excited'?", options: ['期待', '勁', '有趣', '尴尬'], correctIndex: 0 },
    ],
    culturalNote: "Cantonese often uses expressive sounds for emotions!",
  },
  {
    id: 'cantonese-u5-l3',
    dialect: 'cantonese',
    unit: 5,
    lesson: 3,
    title: 'Loving & Hating',
    subtitle: 'Strong feelings',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cne3-1', phrase: { chinese: '愛', romanization: 'oi3', english: 'Love', tone: 3 }},
      { id: 'cne3-2', phrase: { chinese: '憎', romanization: 'zang1', english: 'Hate', tone: 1 }},
      { id: 'cne3-3', phrase: { chinese: '掛住', romanization: 'gwaa3 zyu6', english: 'Miss (someone)', tone: 3 }},
      { id: 'cne3-4', phrase: { chinese: '多謝', romanization: 'do1 ze6', english: 'Thank you', tone: 1 }},
      { id: 'cne3-5', phrase: { chinese: '對唔住', romanization: 'deoi3 m4 zyu6', english: 'Sorry', tone: 4 }},
      { id: 'cne3-6', phrase: { chinese: '原諒', romanization: 'jyun4 loeng6', english: 'Forgive', tone: 4 }},
    ],
    quiz: [
      { id: 'cneq3-1', type: 'listening', question: "What is 'Love'?", options: ['愛', '憎', '掛住', '多謝'], correctIndex: 0 },
      { id: 'cneq3-2', type: 'listening', question: "What is 'Sorry'?", options: ['多謝', '對唔住', '原諒', '掛住'], correctIndex: 1 },
    ],
    culturalNote: "Respect and politeness are very important in Cantonese culture!",
  },
  {
    id: 'cantonese-u5-l4',
    dialect: 'cantonese',
    unit: 5,
    lesson: 4,
    title: 'Feelings & Health',
    subtitle: 'Physical sensations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'cne4-1', phrase: { chinese: '生病', romanization: 'saang1 beng6', english: 'Sick', tone: 1 }},
      { id: 'cne4-2', phrase: { chinese: '頭痛', romanization: 'tau4 tung3', english: 'Headache', tone: 4 }},
      { id: 'cne4-3', phrase: { chinese: '肚痛', romanization: 'tou5 tung3', english: 'Stomachache', tone: 4 }},
      { id: 'cne4-4', phrase: { chinese: '肚餓', romanization: 'tou5 ngo6', english: 'Hungry', tone: 4 }},
      { id: 'cne4-5', phrase: { chinese: '飽', romanization: 'baau2', english: 'Full (ate)', tone: 2 }},
      { id: 'cne4-6', phrase: { chinese: '眼瞓', romanization: 'ngaan6 fan2', english: 'Sleepy', tone: 3 }},
    ],
    quiz: [
      { id: 'cneq4-1', type: 'listening', question: "What is 'Sick'?", options: ['生病', '頭痛', '肚痛', '眼瞓'], correctIndex: 0 },
      { id: 'cneq4-2', type: 'listening', question: "What is 'Hungry'?", options: ['肚餓', '飽', '眼瞓', '肚痛'], correctIndex: 0 },
    ],
    culturalNote: "'食咗未?' (Have you eaten?) is a common Cantonese greeting!",
  },
  {
    id: 'cantonese-u5-l5',
    dialect: 'cantonese',
    unit: 5,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'cneq5-1', type: 'listening', question: "What is 'Happy' in Cantonese?", options: ['開心', '傷心', '擔心', '嬲'], correctIndex: 0 },
      { id: 'cneq5-2', type: 'listening', question: "What is 'Love'?", options: ['憎', '愛', '掛住', '多謝'], correctIndex: 1 },
      { id: 'cneq5-3', type: 'listening', question: "What is 'Sick'?", options: ['生病', '頭痛', '肚痛', '眼瞓'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now express many emotions in Cantonese!",
  },
  // NEW: Hakka Unit 5 - Emotions
  {
    id: 'hakka-u5-l1',
    dialect: 'hakka',
    unit: 5,
    lesson: 1,
    title: 'Happy & Sad',
    subtitle: 'Expressing emotions',
    duration: '6 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hake1-1', phrase: { chinese: '歡喜', romanization: 'fon1 hi3', english: 'Happy', tone: 1 }},
      { id: 'hake1-2', phrase: { chinese: '愁', romanization: 'su2', english: 'Sad', tone: 2 }},
      { id: 'hake1-3', phrase: { chinese: '擔心', romanization: 'dam1 xim1', english: 'Worried', tone: 1 }},
      { id: 'hake1-4', phrase: { chinese: '生氣', romanization: 'sen1 hi4', english: 'Angry', tone: 4 }},
      { id: 'hake1-5', phrase: { chinese: '著驚', romanization: 'cug7 gian1', english: 'Scared', tone: 7 }},
      { id: 'hake1-6', phrase: { chinese: '倦', romanization: 'kian3', english: 'Tired', tone: 3 }},
      { id: 'hake1-7', phrase: { chinese: '毋好過', romanization: 'm2 hou2 guo4', english: 'Uncomfortable', tone: 2 }},
    ],
    dialogue: {
      id: 'hake1-d',
      title: 'Talking About Feelings',
      lines: [
        { speaker: 'A', chinese: '你今日好歡喜喔!', romanization: 'li2 gin1 ngid4 hou2 fon1 hi3 vo3', english: 'You look happy today!' },
        { speaker: 'B', chinese: '因為我搰到工喔!', romanization: 'in1 vi4 ngo5 gut5 dou4 gung1 vo3', english: 'Because I got a job!' },
        { speaker: 'A', chinese: '真好!', romanization: 'zin1 hou2', english: 'Great!' },
      ]
    },
    quiz: [
      { id: 'hakeq1-1', type: 'listening', question: "What is 'Happy' in Hakka?", options: ['歡喜', '愁', '擔心', '生氣'], correctIndex: 0 },
      { id: 'hakeq1-2', type: 'listening', question: "What is 'Angry'?", options: ['著驚', '生氣', '愁', '倦'], correctIndex: 1 },
    ],
    culturalNote: "Hakka expressions are often direct and meaningful!",
  },
  {
    id: 'hakka-u5-l2',
    dialect: 'hakka',
    unit: 5,
    lesson: 2,
    title: 'Surprised & Excited',
    subtitle: 'Strong emotions',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hake2-1', phrase: { chinese: '趣味', romanization: 'qi4 mi4', english: 'Interesting', tone: 4 }},
      { id: 'hake2-2', phrase: { chinese: '讚', romanization: 'zan4', english: 'Amazing', tone: 4 }},
      { id: 'hake2-3', phrase: { chinese: '看下', romanization: 'kan4 ha5', english: 'Embarrassed', tone: 4 }},
      { id: 'hake2-4', phrase: { chinese: '厭', romanization: 'iam4', english: 'Disgusted', tone: 4 }},
      { id: 'hake2-5', phrase: { chinese: '無聊', romanization: 'mo2 liau2', english: 'Bored', tone: 2 }},
      { id: 'hake2-6', phrase: { chinese: '期待', romanization: 'qi1 tai4', english: 'Excited', tone: 4 }},
    ],
    quiz: [
      { id: 'hakeq2-1', type: 'listening', question: "What is 'Interesting'?", options: ['趣味', '無聊', '看下', '厭'], correctIndex: 0 },
      { id: 'hakeq2-2', type: 'listening', question: "What is 'Excited'?", options: ['期待', '讚', '趣味', '看下'], correctIndex: 0 },
    ],
    culturalNote: "Hakka has a rich vocabulary for describing experiences!",
  },
  {
    id: 'hakka-u5-l3',
    dialect: 'hakka',
    unit: 5,
    lesson: 3,
    title: 'Loving & Hating',
    subtitle: 'Strong feelings',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hake3-1', phrase: { chinese: '愛', romanization: 'oi4', english: 'Love', tone: 4 }},
      { id: 'hake3-2', phrase: { chinese: '怨恨', romanization: 'ian4 hen4', english: 'Hate', tone: 4 }},
      { id: 'hake3-3', phrase: { chinese: '思念', romanization: 'su4 ngiam4', english: 'Miss (someone)', tone: 4 }},
      { id: 'hake3-4', phrase: { chinese: '感謝', romanization: 'gam3 qia4', english: 'Grateful', tone: 3 }},
      { id: 'hake3-5', phrase: { chinese: '對毋起', romanization: 'dui4 m2 hi3', english: 'Sorry', tone: 4 }},
      { id: 'hake3-6', phrase: { chinese: '原諒', romanization: 'ngian2 liong6', english: 'Forgive', tone: 2 }},
    ],
    quiz: [
      { id: 'hakeq3-1', type: 'listening', question: "What is 'Love'?", options: ['愛', '怨恨', '思念', '感謝'], correctIndex: 0 },
      { id: 'hakeq3-2', type: 'listening', question: "What is 'Sorry'?", options: ['感謝', '對毋起', '原諒', '思念'], correctIndex: 1 },
    ],
    culturalNote: "Hakka people value honesty and directness in communication!",
  },
  {
    id: 'hakka-u5-l4',
    dialect: 'hakka',
    unit: 5,
    lesson: 4,
    title: 'Feelings & Health',
    subtitle: 'Physical sensations',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hake4-1', phrase: { chinese: '生病', romanization: 'sang1 piang5', english: 'Sick', tone: 1 }},
      { id: 'hake4-2', phrase: { chinese: '頭那痛', romanization: 'teu2 la1 tung4', english: 'Headache', tone: 2 }},
      { id: 'hake4-3', phrase: { chinese: '肚屎痛', romanization: 'tu3 shi3 tung4', english: 'Stomachache', tone: 3 }},
      { id: 'hake4-4', phrase: { chinese: '肚饑', romanization: 'tu3 gi1', english: 'Hungry', tone: 1 }},
      { id: 'hake4-5', phrase: { chinese: '飽', romanization: 'bau3', english: 'Full (ate)', tone: 3 }},
      { id: 'hake4-6', phrase: { chinese: '想睡', romanization: 'siong4 soi4', english: 'Sleepy', tone: 4 }},
    ],
    quiz: [
      { id: 'hakeq4-1', type: 'listening', question: "What is 'Sick'?", options: ['生病', '頭那痛', '肚屎痛', '想睡'], correctIndex: 0 },
      { id: 'hakeq4-2', type: 'listening', question: "What is 'Hungry'?", options: ['肚饑', '飽', '想睡', '頭那痛'], correctIndex: 0 },
    ],
    culturalNote: "'食吔未?' (Have you eaten?) is a common Hakka greeting!",
  },
  {
    id: 'hakka-u5-l5',
    dialect: 'hakka',
    unit: 5,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Test your knowledge',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hakeq5-1', type: 'listening', question: "What is 'Happy' in Hakka?", options: ['歡喜', '愁', '擔心', '生氣'], correctIndex: 0 },
      { id: 'hakeq5-2', type: 'listening', question: "What is 'Love'?", options: ['怨恨', '愛', '思念', '感謝'], correctIndex: 1 },
      { id: 'hakeq5-3', type: 'listening', question: "What is 'Sick'?", options: ['生病', '頭那痛', '肚屎痛', '想睡'], correctIndex: 0 },
    ],
    culturalNote: "Great job! You can now express many emotions in Hakka!",
  },

  // HAKKA UNIT 6: TIME
  {
    id: 'hakka-u6-l1',
    dialect: 'hakka',
    unit: 6,
    lesson: 1,
    title: 'Hours & O\'Clock',
    subtitle: 'Telling the hour',
    duration: '5 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt1-1', phrase: { chinese: '一點', romanization: 'yid1 diam3', english: '1 o\'clock', tone: 1 }},
      { id: 'hkt1-2', phrase: { chinese: '兩點', romanization: 'liang3 diam3', english: '2 o\'clock', tone: 3 }},
      { id: 'hkt1-3', phrase: { chinese: '三點', romanization: 'sam1 diam3', english: '3 o\'clock', tone: 1 }},
      { id: 'hkt1-4', phrase: { chinese: '四點', romanization: 'xi5 diam3', english: '4 o\'clock', tone: 5 }},
      { id: 'hkt1-5', phrase: { chinese: '五點', romanization: 'ng3 diam3', english: '5 o\'clock', tone: 3 }},
      { id: 'hkt1-6', phrase: { chinese: '六點', romanization: 'liu5 diam3', english: '6 o\'clock', tone: 5 }},
      { id: 'hkt1-7', phrase: { chinese: '七點', romanization: 'qid5 diam3', english: '7 o\'clock', tone: 5 }},
    ],
    dialogue: {
      id: 'hktd1',
      title: 'What time is it?',
      lines: [
        { speaker: 'A', chinese: '請問幾點?', romanization: 'qiang3 mun6 gi3 diam3?', english: 'What time is it?' },
        { speaker: 'B', chinese: '三點啊。', romanization: 'sam1 diam3 a.', english: 'It is 3 o\'clock.' },
      ],
    },
    quiz: [
      { id: 'hktq1', type: 'listening', question: "'兩點' means?", options: ['1 o\'clock', '2 o\'clock', '3 o\'clock', '4 o\'clock'], correctIndex: 1 },
    ],
    culturalNote: "Hakka uses 'diam3' (點) for o'clock, similar to Mandarin!",
  },
  {
    id: 'hakka-u6-l2',
    dialect: 'hakka',
    unit: 6,
    lesson: 2,
    title: 'Minutes & Half Hours',
    subtitle: 'Minutes past the hour',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt2-1', phrase: { chinese: '半點', romanization: 'ban5 diam3', english: 'Half past', tone: 5 }},
      { id: 'hkt2-2', phrase: { chinese: '十五分', romanization: 'shib5 ng3 fun1', english: '15 minutes', tone: 5 }},
      { id: 'hkt2-3', phrase: { chinese: '三十分', romanization: 'sam1 shib5 fun1', english: '30 minutes', tone: 1 }},
      { id: 'hkt2-4', phrase: { chinese: '四十五分', romanization: 'xi5 shib5 ng3 fun1', english: '45 minutes', tone: 5 }},
      { id: 'hkt2-5', phrase: { chinese: '一个鐘頭', romanization: 'yid1 ge5 zang1 te2', english: 'One hour', tone: 1 }},
      { id: 'hkt2-6', phrase: { chinese: '兩个鐘頭', romanization: 'liang3 ge5 zang1 te2', english: 'Two hours', tone: 3 }},
    ],
    dialogue: {
      id: 'hktd2',
      title: 'Meeting time',
      lines: [
        { speaker: 'A', chinese: '你幾點愛去?', romanization: 'gi3 diam3 oi5 hi5?', english: 'What time will you go?' },
        { speaker: 'B', chinese: '半點去。', romanization: 'ban5 diam3 hi5.', english: 'I will go at half past.' },
      ],
    },
    quiz: [
      { id: 'hktq2', type: 'listening', question: "'半點' means?", options: ['15 minutes', 'Half past', '45 minutes', 'One hour'], correctIndex: 1 },
    ],
    culturalNote: "In Hakka, '半點' (half past) is commonly used in daily conversation!",
  },
  {
    id: 'hakka-u6-l3',
    dialect: 'hakka',
    unit: 6,
    lesson: 3,
    title: 'Days of the Week',
    subtitle: 'Monday through Sunday',
    duration: '6 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt3-1', phrase: { chinese: '星期一日', romanization: 'xing1 ki2 yid1', english: 'Monday', tone: 1 }},
      { id: 'hkt3-2', phrase: { chinese: '星期兩日', romanization: 'xing1 ki2 liang3', english: 'Tuesday', tone: 3 }},
      { id: 'hkt3-3', phrase: { chinese: '星期三日', romanization: 'xing1 ki2 sam1', english: 'Wednesday', tone: 1 }},
      { id: 'hkt3-4', phrase: { chinese: '星期四日', romanization: 'xing1 ki2 xi5', english: 'Thursday', tone: 5 }},
      { id: 'hkt3-5', phrase: { chinese: '星期五', romanization: 'xing1 ki2 ng3', english: 'Friday', tone: 3 }},
      { id: 'hkt3-6', phrase: { chinese: '星期六', romanization: 'xing1 ki2 liu5', english: 'Saturday', tone: 5 }},
      { id: 'hkt3-7', phrase: { chinese: '星期日', romanization: 'xing1 ki2 ngib7', english: 'Sunday', tone: 7 }},
    ],
    dialogue: {
      id: 'hktd3',
      title: 'Planning the week',
      lines: [
        { speaker: 'A', chinese: '你哪日得閒?', romanization: 'gi3 na1 ngid5 ded5 han2?', english: 'Which day are you free?' },
        { speaker: 'B', chinese: '星期六得閒。', romanization: 'xing1 ki2 liu5 ded5 han2.', english: 'I am free on Saturday.' },
      ],
    },
    quiz: [
      { id: 'hktq3', type: 'listening', question: "'星期五' means?", options: ['Monday', 'Wednesday', 'Friday', 'Sunday'], correctIndex: 2 },
    ],
    culturalNote: "Hakka uses '星期' (xing1 ki2) for week, similar to Mandarin!",
  },
  {
    id: 'hakka-u6-l4',
    dialect: 'hakka',
    unit: 6,
    lesson: 4,
    title: 'Months & Dates',
    subtitle: 'Months and calendar terms',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkt4-1', phrase: { chinese: '一個月', romanization: 'yid1 ge5 ngie7', english: 'One month', tone: 1 }},
      { id: 'hkt4-2', phrase: { chinese: '今日', romanization: 'gin1 ngid5', english: 'Today', tone: 1 }},
      { id: 'hkt4-3', phrase: { chinese: '昨日', romanization: 'cu ngid5', english: 'Yesterday', tone: 7 }},
      { id: 'hkt4-4', phrase: { chinese: '明日', romanization: 'min ngid5', english: 'Tomorrow', tone: 5 }},
      { id: 'hkt4-5', phrase: { chinese: '後日', romanization: 'heu5 ngid5', english: 'Day after tomorrow', tone: 5 }},
      { id: 'hkt4-6', phrase: { chinese: '前日', romanization: 'qien ngid5', english: 'Day before yesterday', tone: 5 }},
    ],
    dialogue: {
      id: 'hktd4',
      title: 'When is the event?',
      lines: [
        { speaker: 'A', chinese: '聚會係哪一日?', romanization: 'qi6 fi6 he6 na1 yid1 ngid5?', english: 'When is the gathering?' },
        { speaker: 'B', chinese: '係明日。', romanization: 'he6 min ngid5.', english: 'It is tomorrow.' },
      ],
    },
    quiz: [
      { id: 'hktq4', type: 'listening', question: "'今日' means?", options: ['Yesterday', 'Today', 'Tomorrow', 'Last week'], correctIndex: 1 },
    ],
    culturalNote: "Hakka '今日' (gin1 ngid5) comes from '今' + '日' - similar to Mandarin!",
  },
  {
    id: 'hakka-u6-l5',
    dialect: 'hakka',
    unit: 6,
    lesson: 5,
    title: 'Time Expressions',
    subtitle: 'Morning, afternoon, evening',
    duration: '5 minutes • 6 phrases',
    xpReward: 100,
    vocabulary: [
      { id: 'hkt5-1', phrase: { chinese: '天光時', romanization: 'tian1 gong1 shi2', english: 'Morning', tone: 1 }},
      { id: 'hkt5-2', phrase: { chinese: '日中時', romanization: 'ngid5 zung1 shi2', english: 'Noon/Afternoon', tone: 1 }},
      { id: 'hkt5-3', phrase: { chinese: '暗晝時', romanization: 'am5 zu5 shi2', english: 'Evening', tone: 5 }},
      { id: 'hkt5-4', phrase: { chinese: '夜裡', romanization: 'ya6 li3', english: 'Night', tone: 6 }},
      { id: 'hkt5-5', phrase: { chinese: '早起', romanization: 'zao3 ki2', english: 'Early morning', tone: 3 }},
      { id: 'hkt5-6', phrase: { chinese: '遲早', romanization: 'chi2 zao3', english: 'Late or early', tone: 2 }},
    ],
    dialogue: {
      id: 'hktd5',
      title: 'When should I come?',
      lines: [
        { speaker: 'A', chinese: '你愛幾時來?', romanization: 'gi3 shi2 loi2?', english: 'When should you come?' },
        { speaker: 'B', chinese: '天光時。', romanization: 'tian1 gong1 shi2.', english: 'In the morning.' },
      ],
    },
    quiz: [
      { id: 'hktq5-1', type: 'listening', question: "'暗晝時' means?", options: ['Morning', 'Noon', 'Evening', 'Night'], correctIndex: 2 },
      { id: 'hktq5-2', type: 'listening', question: "'早起' means?", options: ['Evening', 'Night', 'Early morning', 'Noon'], correctIndex: 2 },
    ],
    culturalNote: "Great job! You can now tell time and make appointments in Hakka!",
  },

  // HAKKA UNIT 7: WEATHER
  {
    id: 'hakka-u7-l1',
    dialect: 'hakka',
    unit: 7,
    lesson: 1,
    title: 'Weather Basics',
    subtitle: 'Hot, cold, warm, cool',
    duration: '5 minutes • 7 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkw1-1', phrase: { chinese: '熱', romanization: 'ngie7', english: 'Hot', tone: 7 }},
      { id: 'hkw1-2', phrase: { chinese: '冷', romanization: 'lan3', english: 'Cold', tone: 3 }},
      { id: 'hkw1-3', phrase: { chinese: '溫暖', romanization: 'un1 non3', english: 'Warm', tone: 1 }},
      { id: 'hkw1-4', phrase: { chinese: '涼', romanization: 'liong2', english: 'Cool', tone: 2 }},
      { id: 'hkw1-5', phrase: { chinese: '好天', romanization: 'hao3 tian1', english: 'Good weather', tone: 3 }},
      { id: 'hkw1-6', phrase: { chinese: '烏陰天', romanization: 'vu1 im1 tian1', english: 'Cloudy', tone: 1 }},
      { id: 'hkw1-7', phrase: { chinese: '落雨天', romanization: 'lo7 yu3 tian1', english: 'Rainy', tone: 7 }},
    ],
    dialogue: {
      id: 'hkbd1',
      title: 'How\'s the weather?',
      lines: [
        { speaker: 'A', chinese: '今日天氣好麼?', romanization: 'gin1 ngid5 tian1 qi5 ho3 ma?', english: 'Is the weather good today?' },
        { speaker: 'B', chinese: '好，幾暖既。', romanization: 'ho3, gi3 non3 ge5.', english: 'Yes, it is quite warm.' },
      ],
    },
    quiz: [
      { id: 'hkwq1', type: 'listening', question: "'冷' means?", options: ['Hot', 'Cold', 'Warm', 'Cool'], correctIndex: 1 },
    ],
    culturalNote: "Hakka weather terms are similar to Mandarin but with different tones!",
  },
  {
    id: 'hakka-u7-l2',
    dialect: 'hakka',
    unit: 7,
    lesson: 2,
    title: 'Rain & Storm',
    subtitle: 'Rainy weather terms',
    duration: '6 minutes • 6 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkw2-1', phrase: { chinese: '雨', romanization: 'yu3', english: 'Rain', tone: 3 }},
      { id: 'hkw2-2', phrase: { chinese: '細雨', romanization: 'xi5 yu3', english: 'Light rain', tone: 5 }},
      { id: 'hkw2-3', phrase: { chinese: '大雨', romanization: 'tai6 yu3', english: 'Heavy rain', tone: 6 }},
      { id: 'hkw2-4', phrase: { chinese: '雷公', romanization: 'lui2 gung1', english: 'Thunder', tone: 2 }},
      { id: 'hkw2-5', phrase: { chinese: '閃電', romanization: 'san3 tien6', english: 'Lightning', tone: 3 }},
      { id: 'hkw2-6', phrase: { chinese: '風', romanization: 'fung1', english: 'Wind', tone: 1 }},
    ],
    dialogue: {
      id: 'hkbd2',
      title: 'It\'s raining',
      lines: [
        { speaker: 'A', chinese: '落雨啊!', romanization: 'lo7 yu3 a!', english: 'It is raining!' },
        { speaker: 'B', chinese: '緊轉大哦!', romanization: 'jin3 zon3 tai6 o!', english: 'It is getting heavy!' },
      ],
    },
    quiz: [
      { id: 'hkwq2', type: 'listening', question: "'大雨' means?", options: ['Light rain', 'Snow', 'Heavy rain', 'Wind'], correctIndex: 2 },
    ],
    culturalNote: "'雷公' (thunder) literally means 'Thunder Lord' in Hakka - fun imagery!",
  },
  {
    id: 'hakka-u7-l3',
    dialect: 'hakka',
    unit: 7,
    lesson: 3,
    title: 'Seasons',
    subtitle: 'Spring, summer, fall, winter',
    duration: '6 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkw3-1', phrase: { chinese: '春天', romanization: 'cun1 tien1', english: 'Spring', tone: 1 }},
      { id: 'hkw3-2', phrase: { chinese: '夏天', romanization: 'ha6 tien1', english: 'Summer', tone: 6 }},
      { id: 'hkw3-3', phrase: { chinese: '秋天', romanization: 'qiu1 tien1', english: 'Fall/Autumn', tone: 1 }},
      { id: 'hkw3-4', phrase: { chinese: '冬天', romanization: 'dung1 tien1', english: 'Winter', tone: 1 }},
      { id: 'hkw3-5', phrase: { chinese: '季節', romanization: 'jie5 jie7', english: 'Season', tone: 5 }},
    ],
    dialogue: {
      id: 'hkbd3',
      title: 'Which season?',
      lines: [
        { speaker: 'A', chinese: '你愛哪一個季節去?', romanization: 'gi3 oi5 na1 yid1 ge5 jie5 jie7 hi5?', english: 'Which season do you like to go?' },
        { speaker: 'B', chinese: '我愛春天。', romanization: 'ngai2 oi5 cun1 tien1.', english: 'I like spring.' },
      ],
    },
    quiz: [
      { id: 'hkwq3', type: 'listening', question: "'夏天' means?", options: ['Spring', 'Summer', 'Fall', 'Winter'], correctIndex: 1 },
    ],
    culturalNote: "Hakka seasons are the same as Mandarin - easy to remember!",
  },
  {
    id: 'hakka-u7-l4',
    dialect: 'hakka',
    unit: 7,
    lesson: 4,
    title: 'Temperature',
    subtitle: 'Describing temperature',
    duration: '5 minutes • 5 phrases',
    xpReward: 50,
    vocabulary: [
      { id: 'hkw4-1', phrase: { chinese: '幾多度?', romanization: 'gi3 do1 du6?', english: 'How many degrees?', tone: 1 }},
      { id: 'hkw4-2', phrase: { chinese: '三十度', romanization: 'sam1 shib5 du6', english: '30 degrees', tone: 1 }},
      { id: 'hkw4-3', phrase: { chinese: '零度', romanization: 'lin2 du6', english: 'Zero degrees', tone: 2 }},
      { id: 'hkw4-4', phrase: { chinese: '零下', romanization: 'lin2 ha6', english: 'Below zero', tone: 6 }},
      { id: 'hkw4-5', phrase: { chinese: '溫度', romanization: 'un1 du6', english: 'Temperature', tone: 1 }},
    ],
    dialogue: {
      id: 'hkbd4',
      title: 'How hot is it?',
      lines: [
        { speaker: 'A', chinese: '今日幾多度?', romanization: 'gin1 ngid5 gi3 do1 du6?', english: 'How many degrees is it today?' },
        { speaker: 'B', chinese: '三十度。', romanization: 'sam1 shib5 du6.', english: '30 degrees.' },
      ],
    },
    quiz: [
      { id: 'hkwq4', type: 'listening', question: "'零下' means?", options: ['Zero', 'Above zero', 'Below zero', 'Temperature'], correctIndex: 2 },
    ],
    culturalNote: "Hakka uses similar temperature terms to Mandarin - helpful for Mandarin speakers!",
  },
  {
    id: 'hakka-u7-l5',
    dialect: 'hakka',
    unit: 7,
    lesson: 5,
    title: 'Unit Review',
    subtitle: 'Weather review',
    duration: '5 minutes',
    xpReward: 100,
    vocabulary: [],
    quiz: [
      { id: 'hkwq5-1', type: 'listening', question: "'好天' means?", options: ['Rainy', 'Good weather', 'Cloudy', 'Stormy'], correctIndex: 1 },
      { id: 'hkwq5-2', type: 'listening', question: "'冬天' means?", options: ['Spring', 'Summer', 'Fall', 'Winter'], correctIndex: 3 },
      { id: 'hkwq5-3', type: 'listening', question: "'閃電' means?", options: ['Rain', 'Thunder', 'Lightning', 'Wind'], correctIndex: 2 },
    ],
    culturalNote: "Congratulations! You can now talk about weather and seasons in Hakka!",
  },
];

// Helper functions
export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find(l => l.id === id);
}

export function getLessonsByUnit(dialect: Dialect, unit: number): Lesson[] {
  return LESSONS.filter(l => l.dialect === dialect && l.unit === unit);
}

export function getUnitById(id: string): Unit | undefined {
  return UNITS.find(u => u.id === id);
}

export function getNextLesson(currentLessonId: string): Lesson | null {
  const currentIndex = LESSONS.findIndex(l => l.id === currentLessonId);
  if (currentIndex === -1 || currentIndex === LESSONS.length - 1) return null;
  return LESSONS[currentIndex + 1];
}




